import { Article } from '@/types'

export const articles: Article[] = [
  {
    id: '1',
    title: 'Scientists Develop Revolutionary Coral Restoration Technique That Could Save Reefs Worldwide',
    summary: 'Marine biologists in Australia have pioneered a breakthrough method to accelerate coral growth by 40x, offering new hope for the Great Barrier Reef and coral ecosystems globally.',
    content: 'A team of marine biologists at the Australian Institute of Marine Science has developed a groundbreaking coral restoration technique that could transform reef conservation efforts worldwide. The method, which combines selective breeding with micro-fragmentation technology, accelerates coral growth by up to 40 times the natural rate. The team has already successfully restored over 50,000 square meters of damaged reef in pilot programs along the Great Barrier Reef. Coral expert Dr. Sarah Chen called the results "nothing short of miraculous," noting that corals that previously took decades to grow are now thriving within months. The technique is being shared freely with conservation groups in 30 countries, with training programs underway in the Caribbean, Southeast Asia, and the Pacific Islands.',
    sourceUrl: 'https://example.com/coral-restoration',
    sourceName: 'Science Daily',
    region: 'Oceania',
    country: 'Australia',
    category: 'Environment',
    tags: ['ocean', 'conservation', 'marine life', 'climate', 'innovation'],
    publishedAt: '2026-03-06T08:00:00Z',
    imageUrl: 'https://picsum.photos/seed/coral/800/450',
    positivityScore: 98,
    trending: true,
    featured: true,
    readTime: 4,
  },
  {
    id: '2',
    title: 'Community Garden Network Transforms 200 Urban Food Deserts Across North America',
    summary: 'A volunteer-driven initiative has converted abandoned lots in 200 cities into thriving community gardens, providing fresh produce to over 500,000 residents who previously had no access to healthy food.',
    content: 'What started as a single garden in Detroit five years ago has blossomed into a continent-wide movement. The Urban Roots Network now operates 200 community gardens across North American cities, turning neglected spaces into green sanctuaries that feed hundreds of thousands of families. Each garden is managed by local volunteers trained in sustainable agriculture, and surplus produce is donated to food banks and schools. The initiative has not only improved nutrition in underserved communities but also reduced urban heat island effects and created new social spaces where neighbors connect. Local governments have taken notice, with 35 cities now partnering with Urban Roots to offer subsidized land leases and startup funding.',
    sourceUrl: 'https://example.com/urban-gardens',
    sourceName: 'The Guardian',
    region: 'North America',
    country: 'United States',
    category: 'Community',
    tags: ['food security', 'urban farming', 'community', 'sustainability', 'volunteering'],
    publishedAt: '2026-03-05T10:30:00Z',
    imageUrl: 'https://picsum.photos/seed/garden/800/450',
    positivityScore: 95,
    trending: true,
    featured: true,
    readTime: 3,
  },
  {
    id: '3',
    title: '16-Year-Old Inventor Creates $5 Water Purifier Now Deployed in 12 African Nations',
    summary: 'Teenage engineer Amara Diallo from Senegal designed an ultra-low-cost solar-powered water purification device using locally available materials, now providing clean water to over 2 million people.',
    content: 'Amara Diallo was 14 when she watched her younger sister fall ill from contaminated water. Two years later, her invention is changing lives across an entire continent. Using salvaged materials and a novel solar-UV purification method, Amara created a device that produces 50 liters of clean water per day for just $5 in manufacturing costs. UNICEF and several NGOs have partnered to mass-produce and distribute the device across 12 sub-Saharan African nations. The design is open-source, allowing local artisans to build and maintain units using materials available in local markets. Amara, now 16, has been invited to speak at the United Nations and was awarded the Young Innovator Prize at the World Science Forum.',
    sourceUrl: 'https://example.com/water-purifier',
    sourceName: 'BBC News',
    region: 'Africa',
    country: 'Senegal',
    category: 'Science & Tech',
    tags: ['innovation', 'clean water', 'youth', 'Africa', 'invention'],
    publishedAt: '2026-03-05T07:15:00Z',
    imageUrl: 'https://picsum.photos/seed/water/800/450',
    positivityScore: 99,
    trending: true,
    featured: true,
    readTime: 4,
  },
  {
    id: '4',
    title: 'Portugal Becomes First European Nation to Run on 100% Renewable Energy for Full Year',
    summary: 'In a landmark achievement for clean energy, Portugal has completed a full calendar year powered entirely by wind, solar, and hydroelectric sources, setting a record for any EU nation.',
    content: 'Portugal has achieved what many believed impossible just a decade ago: operating its entire national grid on renewable energy for 365 consecutive days. The milestone, confirmed by national grid operator REN, was reached through a combination of expanded offshore wind farms, solar installations across the Alentejo region, and modernized hydroelectric infrastructure. The achievement has significantly reduced Portugal\'s carbon emissions and has lowered household electricity bills by an average of 18%. Energy Minister Ricardo Flores described it as "a gift to our children and grandchildren." Other European nations, including Spain and Greece, have announced accelerated plans inspired by Portugal\'s success, signaling a potential regional shift toward full renewable energy.',
    sourceUrl: 'https://example.com/portugal-renewable',
    sourceName: 'Reuters',
    region: 'Europe',
    country: 'Portugal',
    category: 'Environment',
    tags: ['renewable energy', 'climate', 'sustainability', 'Europe', 'clean energy'],
    publishedAt: '2026-03-04T14:00:00Z',
    imageUrl: 'https://picsum.photos/seed/solar/800/450',
    positivityScore: 97,
    trending: true,
    featured: false,
    readTime: 3,
  },
  {
    id: '5',
    title: 'New mRNA Cancer Vaccine Shows 90% Success Rate in Phase III Trials',
    summary: 'Building on COVID-19 vaccine technology, researchers have developed a personalized mRNA cancer vaccine that successfully prevented recurrence in 90% of patients across 12 cancer types in landmark trials.',
    content: 'In what oncologists are calling the most significant cancer breakthrough in a generation, researchers from the BioNTech-Moderna consortium have published Phase III results for a personalized mRNA cancer vaccine with a 90% success rate in preventing cancer recurrence. The vaccine, which is tailored to each patient\'s specific tumor mutations, was tested across 2,400 patients with 12 different cancer types, including melanoma, lung, and colorectal cancers. Unlike traditional chemotherapy, the vaccine works by training the immune system to recognize and destroy cancer cells with minimal side effects. The FDA has granted breakthrough therapy designation, and the European Medicines Agency is on track to approve the treatment by year\'s end. Researchers estimate the vaccine could prevent over 500,000 cancer deaths annually.',
    sourceUrl: 'https://example.com/cancer-vaccine',
    sourceName: 'Nature Medicine',
    region: 'Global',
    country: 'International',
    category: 'Health',
    tags: ['cancer', 'vaccine', 'medicine', 'mRNA', 'breakthrough'],
    publishedAt: '2026-03-04T11:00:00Z',
    imageUrl: 'https://picsum.photos/seed/medicine/800/450',
    positivityScore: 99,
    trending: true,
    featured: true,
    readTime: 5,
  },
  {
    id: '6',
    title: 'Indian Village Plants 1 Million Trees in 24 Hours, Breaking World Record',
    summary: 'The community of Khunti in Jharkhand, India, mobilized 300,000 volunteers to plant one million native trees in a single day, restoring a forest corridor vital to local wildlife.',
    content: 'The village of Khunti has achieved what no community has managed before: planting one million trees in just 24 hours through an extraordinary display of collective will. Organized by local environmental leader Sunita Devi, the effort engaged 300,000 volunteers from across the region who worked through the night to plant native species including teak, neem, and peepal trees across 2,000 hectares. The newly planted forest will restore a critical wildlife corridor connecting two national parks, providing habitat for tigers, leopards, and hundreds of bird species. State forestry officials confirmed the plants were properly spaced and cared for, not symbolic plantings, and will receive five years of maintenance from community forest committees. The Guinness World Records team was present to verify the achievement.',
    sourceUrl: 'https://example.com/india-trees',
    sourceName: 'The Hindu',
    region: 'Asia',
    country: 'India',
    category: 'Environment',
    tags: ['reforestation', 'India', 'community', 'wildlife', 'record'],
    publishedAt: '2026-03-03T09:00:00Z',
    imageUrl: 'https://picsum.photos/seed/trees/800/450',
    positivityScore: 96,
    trending: false,
    featured: false,
    readTime: 3,
  },
  {
    id: '7',
    title: 'Vienna Bakery\'s "Pay It Forward" Program Has Fed 50,000 Homeless People for Free',
    summary: 'Bäckerei Hartmann in Vienna introduced a simple wall of sticky notes where customers prepay meals for anyone in need — five years later, it has become a citywide movement serving thousands weekly.',
    content: 'When baker Franz Hartmann introduced a "pay it forward" wall in his small Viennese bakery in 2021, he hoped it might help a few struggling neighbors. He could not have imagined it would grow into a city-defining institution. Five years on, the bakery\'s original initiative has spread to 47 partner businesses across Vienna, creating a network where anyone experiencing hunger can walk in and receive a hot meal or groceries — no questions asked. The program has served over 50,000 meals and operates on a simple premise: customers buy a token and pin it to the wall; anyone who needs it takes one. The Vienna city government recently awarded the program a cultural prize and allocated funding to expand it to other Austrian cities.',
    sourceUrl: 'https://example.com/vienna-bakery',
    sourceName: 'Der Standard',
    region: 'Europe',
    country: 'Austria',
    category: 'Community',
    tags: ['community', 'homelessness', 'kindness', 'food', 'Austria'],
    publishedAt: '2026-03-03T15:30:00Z',
    imageUrl: 'https://picsum.photos/seed/bakery/800/450',
    positivityScore: 97,
    trending: false,
    featured: false,
    readTime: 3,
  },
  {
    id: '8',
    title: 'AI System Detects Alzheimer\'s 15 Years Before Symptoms Appear with 94% Accuracy',
    summary: 'Researchers at Johns Hopkins have developed an AI diagnostic tool that identifies early biomarkers of Alzheimer\'s disease up to 15 years before clinical symptoms, opening a new era of prevention.',
    content: 'A breakthrough AI diagnostic system developed at Johns Hopkins University can identify Alzheimer\'s disease 15 years before the first symptoms appear, offering the possibility of early intervention that could dramatically slow or halt its progression. The system, trained on 100,000 brain scans and cerebrospinal fluid analyses, detects subtle protein accumulation patterns invisible to human radiologists with 94% accuracy. In a five-year validation study involving 8,000 participants, the AI identified every case that later developed Alzheimer\'s at the 15-year mark. Neurologist Dr. Maya Rodriguez called it "a paradigm shift in dementia care," noting that current treatments are far more effective at early stages. The FDA has fast-tracked regulatory review and clinical deployment is expected within 18 months.',
    sourceUrl: 'https://example.com/alzheimers-ai',
    sourceName: 'JAMA Neurology',
    region: 'North America',
    country: 'United States',
    category: 'Science & Tech',
    tags: ['AI', 'Alzheimer\'s', 'health', 'neurology', 'prevention'],
    publishedAt: '2026-03-02T12:00:00Z',
    imageUrl: 'https://picsum.photos/seed/brain/800/450',
    positivityScore: 95,
    trending: true,
    featured: false,
    readTime: 4,
  },
  {
    id: '9',
    title: 'Scientists Discover Thriving Deep-Sea Ecosystem Larger Than Amazon Rainforest',
    summary: 'A deep-ocean survey using autonomous submarines has revealed a previously unknown ecosystem in the Pacific covering 8 million square kilometers, teeming with undiscovered species.',
    content: 'In what oceanographers are calling the most significant marine discovery of the century, a two-year autonomous submarine survey has mapped a vast deep-sea ecosystem in the central Pacific that covers approximately 8 million square kilometers — larger than the Amazon rainforest. The survey, conducted by an international consortium of 22 research institutions, has identified over 5,000 species never before catalogued, including bioluminescent corals, novel crustaceans, and extraordinary filter-feeding organisms adapted to extreme pressure and darkness. Far from being a barren wasteland, the ecosystem appears to play a crucial role in global carbon cycling, potentially storing hundreds of gigatons of carbon. Marine biologist Dr. Keiko Tanaka said the discovery "rewrites our understanding of life on Earth." International protections for the area are being fast-tracked through the UN Ocean Treaty.',
    sourceUrl: 'https://example.com/deep-sea-ecosystem',
    sourceName: 'Nature',
    region: 'Global',
    country: 'International',
    category: 'Science & Tech',
    tags: ['ocean', 'discovery', 'biodiversity', 'science', 'ecology'],
    publishedAt: '2026-03-02T08:45:00Z',
    imageUrl: 'https://picsum.photos/seed/ocean/800/450',
    positivityScore: 94,
    trending: true,
    featured: false,
    readTime: 5,
  },
  {
    id: '10',
    title: 'Literacy Rates Among Children in Sub-Saharan Africa Reach Historic High of 89%',
    summary: 'A decade of investment in community schools, teacher training, and mobile education programs has raised literacy rates among 6-14 year olds in sub-Saharan Africa from 52% to 89% — the fastest improvement ever recorded.',
    content: 'A decade-long coordinated education initiative across 22 sub-Saharan African nations has produced results described by UNESCO as "the greatest improvement in literacy in recorded history." Literacy rates among children aged 6 to 14 have risen from 52% in 2016 to 89% today, with particularly dramatic gains in rural areas. The achievement was driven by a combination of community-built schools, accelerated teacher training programs that certified 180,000 new educators, and solar-powered tablet programs that brought interactive learning to even the most remote villages. Girls\' literacy rates improved at twice the pace of boys\', closing a long-standing gap. World Bank economists estimate the productivity gains from this literacy surge will add $2 trillion to African economies over the next 30 years.',
    sourceUrl: 'https://example.com/africa-literacy',
    sourceName: 'UNESCO Report',
    region: 'Africa',
    country: 'Sub-Saharan Africa',
    category: 'Education',
    tags: ['education', 'literacy', 'Africa', 'children', 'progress'],
    publishedAt: '2026-03-01T10:00:00Z',
    imageUrl: 'https://picsum.photos/seed/school/800/450',
    positivityScore: 98,
    trending: false,
    featured: true,
    readTime: 4,
  },
  {
    id: '11',
    title: 'Solar-Powered Hospital Opens in Remote Kenyan Region, Serving 400,000 Previously Unreached Residents',
    summary: 'The first fully solar-powered hospital in East Africa has opened in Marsabit County, bringing specialist healthcare including surgery and maternity care to 400,000 people who previously had no access.',
    content: 'For decades, the 400,000 residents of Marsabit County in northern Kenya had to travel over 400 kilometers to reach the nearest hospital. That changed with the opening of Marsabit Solar Medical Center — East Africa\'s first fully solar-powered hospital, capable of performing surgeries, managing complex pregnancies, and treating conditions previously requiring costly evacuations to Nairobi. The 120-bed facility runs entirely on a 500-kilowatt solar array with battery backup, making it immune to grid outages. Built through a partnership between the Kenyan government, MSF, and the Gates Foundation, the hospital employs 85 local staff trained at partner institutions. In its first month of operation, the maternity ward has already delivered 147 babies under sterile conditions — compared to zero in the previous year.',
    sourceUrl: 'https://example.com/kenya-hospital',
    sourceName: 'Al Jazeera',
    region: 'Africa',
    country: 'Kenya',
    category: 'Health',
    tags: ['healthcare', 'solar energy', 'Kenya', 'Africa', 'access'],
    publishedAt: '2026-02-28T13:00:00Z',
    imageUrl: 'https://picsum.photos/seed/hospital/800/450',
    positivityScore: 97,
    trending: false,
    featured: false,
    readTime: 4,
  },
  {
    id: '12',
    title: 'Brazilian Olympic Champion Donates Prize Money to Build 15 Sports Centers in Favelas',
    summary: 'Marathon gold medalist Fernanda Costa has donated her entire Olympic earnings and secured $20M in corporate sponsorships to build 15 free sports and education centers across Rio\'s underserved communities.',
    content: 'When Fernanda Costa crossed the finish line in Paris and won Brazil\'s first Olympic marathon gold in 24 years, she immediately knew what she would do with the prize money. Instead of a luxury vacation or endorsement-driven retirement, Costa channeled every dollar into a foundation she had been building for years. The 15 Comunidade Sports Centers now under construction across Rio de Janeiro\'s most underserved communities will offer free athletics training, after-school tutoring, and mental health support to over 30,000 young people annually. Corporate sponsors inspired by Costa\'s commitment have added $20 million to the foundation\'s funds. Costa, who grew up in the very favelas being served, says she sees the centers as "the medal that will still be standing in 100 years."',
    sourceUrl: 'https://example.com/fernanda-costa',
    sourceName: 'ESPN Brazil',
    region: 'Latin America',
    country: 'Brazil',
    category: 'Sports',
    tags: ['olympics', 'charity', 'Brazil', 'youth', 'community'],
    publishedAt: '2026-02-27T09:30:00Z',
    imageUrl: 'https://picsum.photos/seed/sports/800/450',
    positivityScore: 96,
    trending: false,
    featured: false,
    readTime: 3,
  },
  {
    id: '13',
    title: 'UN Resettlement Program Successfully Finds Permanent Homes for Record 1.2 Million Refugees',
    summary: 'The UNHCR\'s expanded resettlement initiative achieved a historic milestone, placing 1.2 million refugees in permanent homes across 45 countries in a single year — a 300% increase over 2020 numbers.',
    content: 'The United Nations Refugee Agency announced that 2025 saw the successful permanent resettlement of 1.2 million refugees — the highest number ever achieved and a 300% increase over 2020 levels. The milestone was made possible by a new "resettlement compact" signed by 45 nations pledging increased quotas, combined with innovative job-matching programs that connected refugees with skills-based immigration pathways. New receiving countries including Japan, South Korea, and several Gulf states significantly expanded their programs. Data shows that 78% of resettled refugees from the 2023 cohort are now employed, 94% of their children are enrolled in school, and their economic contribution to host nations exceeds resettlement costs within three years. UNHCR Commissioner Amina Warsame called it "proof that compassion and practicality are not opposites."',
    sourceUrl: 'https://example.com/unhcr-resettlement',
    sourceName: 'UNHCR',
    region: 'Global',
    country: 'International',
    category: 'Humanitarian',
    tags: ['refugees', 'humanitarian', 'UN', 'resettlement', 'hope'],
    publishedAt: '2026-02-26T11:00:00Z',
    imageUrl: 'https://picsum.photos/seed/refugee/800/450',
    positivityScore: 94,
    trending: false,
    featured: false,
    readTime: 4,
  },
  {
    id: '14',
    title: 'Philippines Discovers Pristine Coral Triangle Reef System Untouched by Human Activity',
    summary: 'Marine surveyors exploring a remote section of the Coral Triangle have found a 3,000-square-kilometer reef system in near-perfect health, providing a blueprint for global reef restoration.',
    content: 'Scientists conducting biodiversity surveys in a remote section of the Coral Triangle have stumbled upon one of the greatest marine conservation finds of the decade: a 3,000-square-kilometer reef system showing almost no signs of human disturbance. Located in waters between the Philippines and Palau, the reef boasts coral coverage exceeding 80% — compared to a global average of less than 30% — and teems with species including whale sharks, manta rays, and multiple species of sea turtles. Researchers believe its pristine state is due to its isolation and depth, making it inaccessible to most fishing vessels. The Philippine government immediately declared the area a Marine Protected Area and is working with Palau and international partners to create a joint ocean sanctuary. Scientists hope the reef will serve as a "seed bank" for restoration efforts across degraded reefs throughout the region.',
    sourceUrl: 'https://example.com/coral-triangle',
    sourceName: 'National Geographic',
    region: 'Asia',
    country: 'Philippines',
    category: 'Environment',
    tags: ['coral reef', 'ocean', 'Philippines', 'biodiversity', 'conservation'],
    publishedAt: '2026-02-25T08:00:00Z',
    imageUrl: 'https://picsum.photos/seed/reef/800/450',
    positivityScore: 95,
    trending: false,
    featured: false,
    readTime: 4,
  },
  {
    id: '15',
    title: 'Amsterdam Converts 5,000 Parking Spaces Into Parks and Bike Lanes in Bold Green Overhaul',
    summary: 'Amsterdam\'s ambitious urban transformation plan has converted 5,000 car parking spaces into mini-parks, playgrounds, and cycle lanes, dramatically improving quality of life and air quality in the city center.',
    content: 'Amsterdam has completed the most ambitious urban de-paving project in European history, converting 5,000 city-center parking spaces into green spaces, playgrounds, outdoor dining areas, and expanded bicycle infrastructure. The transformation, rolled out over three years, was approved by 73% of residents in a citywide referendum and has delivered measurable results: city center air quality has improved by 34%, road traffic accidents have fallen by 28%, and street-level temperatures are down an average of 3°C in summer. The newly planted trees and rain gardens have also helped manage storm water, preventing a projected 40 annual basement floods. Business associations initially feared reduced footfall but reported a 12% increase in retail sales as more pedestrians and cyclists move through streets. The project is now being studied by 60 cities worldwide as a model for urban transformation.',
    sourceUrl: 'https://example.com/amsterdam-green',
    sourceName: 'NRC Handelsblad',
    region: 'Europe',
    country: 'Netherlands',
    category: 'Environment',
    tags: ['urban planning', 'Netherlands', 'cycling', 'green city', 'sustainability'],
    publishedAt: '2026-02-24T14:30:00Z',
    imageUrl: 'https://picsum.photos/seed/amsterdam/800/450',
    positivityScore: 93,
    trending: false,
    featured: false,
    readTime: 3,
  },
  {
    id: '16',
    title: 'Syrian Refugee Artist\'s Murals Transform Jordanian Camp Into "World\'s Largest Outdoor Gallery"',
    summary: 'Artist Layla Al-Hassan has spent three years painting massive, vibrant murals across Zaatari refugee camp with 300 fellow residents, turning it into a celebrated outdoor art destination visited by tourists worldwide.',
    content: 'What began as one woman\'s act of defiance against despair has grown into an internationally recognized cultural movement. Over three years, Syrian refugee and former art teacher Layla Al-Hassan has coordinated the painting of 240 murals across Zaatari refugee camp in Jordan, transforming its concrete walls into a sweeping visual narrative of resilience, memory, and hope. Working with 300 fellow camp residents — many of whom had never held a paintbrush — Layla organized workshops, sourced donated materials, and curated a visual language that blends Syrian artistic traditions with contemporary expression. The camp is now visited by international tourists, and proceeds from guided art tours are distributed to participating families. Three of the artists have received scholarships to European art schools, and the project has inspired similar art initiatives in camps in Lebanon, Turkey, and Uganda.',
    sourceUrl: 'https://example.com/zaatari-art',
    sourceName: 'Le Monde',
    region: 'Middle East',
    country: 'Jordan',
    category: 'Arts & Culture',
    tags: ['art', 'refugees', 'Syria', 'Jordan', 'resilience'],
    publishedAt: '2026-02-23T11:15:00Z',
    imageUrl: 'https://picsum.photos/seed/mural/800/450',
    positivityScore: 96,
    trending: false,
    featured: false,
    readTime: 4,
  },
  {
    id: '17',
    title: 'Chinese Startup\'s Sodium-Ion Battery Charges Electric Vehicles in 8 Minutes',
    summary: 'CATL\'s new generation sodium-ion battery achieves an 8-minute full charge for electric vehicles with a 600km range, at 40% lower cost than lithium-ion — a potential turning point for global EV adoption.',
    content: 'Chinese battery giant CATL has announced a sodium-ion battery for electric vehicles that can be fully charged in just 8 minutes and delivers a range of 600 kilometers — figures that eclipse the best lithium-ion batteries currently available. The breakthrough addresses the two biggest barriers to EV adoption: charging speed and cost. Because sodium is abundant globally and does not require cobalt or lithium mining, the batteries cost 40% less to manufacture than current lithium-ion cells. Environmental assessments show a 60% lower carbon footprint across the battery\'s lifecycle. CATL has announced partnerships with Toyota, Volkswagen, and Ford to integrate the batteries into mainstream vehicles by 2027. Analysts say the announcement could make internal combustion engine vehicles economically uncompetitive within a decade.',
    sourceUrl: 'https://example.com/sodium-battery',
    sourceName: 'TechCrunch',
    region: 'Asia',
    country: 'China',
    category: 'Science & Tech',
    tags: ['EV', 'battery', 'clean energy', 'innovation', 'transport'],
    publishedAt: '2026-02-22T09:00:00Z',
    imageUrl: 'https://picsum.photos/seed/battery/800/450',
    positivityScore: 94,
    trending: true,
    featured: false,
    readTime: 4,
  },
  {
    id: '18',
    title: 'Costa Rican Community Saves Critically Endangered Sea Turtle from Extinction',
    summary: 'A decade-long community-led conservation program in Tortuguero has brought the leatherback sea turtle population from 250 nesting females to over 2,400, celebrating one of conservation\'s greatest comebacks.',
    content: 'Ten years ago, fewer than 250 leatherback sea turtles were returning annually to nest on Costa Rica\'s Tortuguero beach — a population so small that biologists feared extinction within a generation. Today, the number exceeds 2,400, representing one of the most successful marine conservation recoveries in history. The turnaround was achieved not through government mandates but through a community-owned conservation model that converted former poachers and egg harvesters into paid turtle guardians. Families who once relied on turtle eggs for income now earn more as certified conservation guides and patrol volunteers. Plastic removal programs have cleared 40 tons of debris from nesting beaches, and boat speed regulations protect turtles from propeller strikes offshore. The Tortuguero model is now being replicated in 14 countries across the Caribbean, Pacific, and Indian Oceans.',
    sourceUrl: 'https://example.com/sea-turtle',
    sourceName: 'The Nature Conservancy',
    region: 'Latin America',
    country: 'Costa Rica',
    category: 'Environment',
    tags: ['sea turtles', 'conservation', 'Costa Rica', 'ocean', 'community'],
    publishedAt: '2026-02-21T12:00:00Z',
    imageUrl: 'https://picsum.photos/seed/turtle/800/450',
    positivityScore: 97,
    trending: false,
    featured: false,
    readTime: 4,
  },
  {
    id: '19',
    title: 'App Connecting Elderly with Nearby Volunteers Reaches 2 Million Users Across 30 Countries',
    summary: '"Neighbor Up" — a free app that matches isolated elderly residents with local volunteers for errands, companionship, and tech help — has reduced loneliness and emergency hospitalizations in pilot cities by 35%.',
    content: 'Loneliness among the elderly has been called a public health epidemic, with studies linking it to cognitive decline, heart disease, and early mortality. "Neighbor Up," launched by a team of social work students in Toronto in 2023, has quietly become one of the most impactful social apps ever built. The platform matches elderly users with verified local volunteers for grocery runs, medical appointment transport, technology assistance, and simple companionship visits. With 2 million active users across 30 countries, the app has facilitated over 15 million volunteer hours and demonstrated measurable public health benefits: a 35% reduction in emergency hospitalizations and 42% drop in self-reported loneliness among regular users. Healthcare systems in Canada, the UK, and New Zealand have begun officially prescribing the app as part of social prescribing programs.',
    sourceUrl: 'https://example.com/neighbor-up',
    sourceName: 'CBC News',
    region: 'North America',
    country: 'Canada',
    category: 'Community',
    tags: ['elderly', 'loneliness', 'volunteering', 'app', 'community'],
    publishedAt: '2026-02-20T10:00:00Z',
    imageUrl: 'https://picsum.photos/seed/volunteer/800/450',
    positivityScore: 95,
    trending: false,
    featured: false,
    readTime: 4,
  },
  {
    id: '20',
    title: 'Vietnam\'s Poverty Rate Drops to 2.3% — The Fastest Decline in Asian History',
    summary: 'Vietnam has reduced extreme poverty from 58% in 1990 to just 2.3% in 2025, lifting 80 million people out of poverty through education-first policies, export-led growth, and universal healthcare expansion.',
    content: 'The World Bank has released a report confirming Vietnam as the most successful poverty reduction story in recorded history, with the share of its population living in extreme poverty falling from 58% in 1990 to just 2.3% today — a decline that lifted 80 million people out of destitution in 35 years. The achievement was driven by a combination of universal primary education investment, strategic export-oriented industrialization, comprehensive land reform that gave smallholder farmers property rights, and universal health coverage introduced in 2015. Infant mortality has fallen from 51 per 1,000 in 1990 to 14 today, and secondary school enrollment now exceeds 96%. Researchers point to Vietnam\'s success as a blueprint combining market-oriented economics with strong public investment, with lessons applicable across the developing world.',
    sourceUrl: 'https://example.com/vietnam-poverty',
    sourceName: 'World Bank Report',
    region: 'Asia',
    country: 'Vietnam',
    category: 'Humanitarian',
    tags: ['poverty', 'development', 'Vietnam', 'progress', 'Asia'],
    publishedAt: '2026-02-19T08:30:00Z',
    imageUrl: 'https://picsum.photos/seed/vietnam/800/450',
    positivityScore: 96,
    trending: false,
    featured: false,
    readTime: 4,
  },
  {
    id: '21',
    title: 'MIT Students Design $50 3D-Printed Prosthetic Arm That Rivals $70,000 Devices',
    summary: 'A team of biomedical engineering students at MIT has created a functional, fully articulating prosthetic arm that costs $50 to print and assemble, featuring grip strength comparable to industry-standard devices costing 1,400 times more.',
    content: 'For the 2.6 million Americans and 57 million people worldwide living with limb loss, the cost of advanced prosthetics — often $70,000 or more — has meant that function and independence remain out of reach for most. A team of MIT biomedical engineering students may have changed that equation forever. Their open-source 3D-printed prosthetic arm, named "OpenHand," costs just $50 in materials, uses standard electronics components available worldwide, and in clinical testing has demonstrated grip strength and precision comparable to commercial devices costing 1,400 times more. The entire design is published under a Creative Commons license, meaning any community worldwide with access to a 3D printer can produce it locally. Early deployment programs are underway in Cambodia, Mozambique, and Haiti, with 3,000 arms already distributed.',
    sourceUrl: 'https://example.com/prosthetic-arm',
    sourceName: 'MIT News',
    region: 'North America',
    country: 'United States',
    category: 'Science & Tech',
    tags: ['prosthetics', 'MIT', '3D printing', 'innovation', 'accessibility'],
    publishedAt: '2026-02-18T11:30:00Z',
    imageUrl: 'https://picsum.photos/seed/prosthetic/800/450',
    positivityScore: 98,
    trending: true,
    featured: false,
    readTime: 4,
  },
  {
    id: '22',
    title: 'World Food Programme Reaches Milestone: 1 Billion Meals Served in Single Year',
    summary: 'The WFP has surpassed 1 billion meals delivered in a 12-month period for the first time in its history, aided by a record $7.2 billion in contributions and AI-powered logistics improvements that cut food waste by 60%.',
    content: 'The United Nations World Food Programme has delivered over 1 billion meals in a single year for the first time in its 60-year history, reaching 152 million people across 81 countries experiencing acute food insecurity. The achievement was made possible by record-breaking donor contributions totaling $7.2 billion — including first-ever commitments from tech companies pledging 1% of annual revenue — combined with revolutionary AI-powered supply chain improvements that reduced food spoilage and waste by 60%. New cold-chain logistics partnerships with local entrepreneurs have enabled fresh food delivery to previously unreachable communities. WFP Executive Director Cindy McCain called it "a turning point not just for food relief, but for how the world collaborates around hunger." Economists estimate that for every $1 invested in WFP programs, $9 in economic productivity is returned through healthier, more capable populations.',
    sourceUrl: 'https://example.com/wfp-milestone',
    sourceName: 'WFP',
    region: 'Global',
    country: 'International',
    category: 'Humanitarian',
    tags: ['hunger', 'food security', 'UN', 'humanitarian', 'milestone'],
    publishedAt: '2026-02-17T14:00:00Z',
    imageUrl: 'https://picsum.photos/seed/food/800/450',
    positivityScore: 96,
    trending: false,
    featured: false,
    readTime: 4,
  },
  {
    id: '23',
    title: 'Colombia\'s Amazon Deforestation Rate Drops 94% Through Community Land Rights Program',
    summary: 'Colombia has virtually halted Amazon deforestation by legally titling 12 million hectares to indigenous communities, demonstrating that land rights are the most effective conservation tool ever discovered.',
    content: 'Colombia has achieved something that decades of government enforcement, satellite monitoring, and international pressure could not: a 94% reduction in Amazon deforestation, achieved not through top-down intervention but by recognizing the land rights of the people who have protected the forest for centuries. The national land titling program, which granted legal rights to 12 million hectares across 140 indigenous and Afro-Colombian communities, has produced deforestation rates lower than any comparable region on Earth. Satellite data confirms that legally titled indigenous territories experience 3.7 times less deforestation than protected areas managed by government agencies. Community forest rangers have replaced illegal loggers as the dominant presence in the forest, and ecotourism programs are generating incomes that make sustainable land use economically superior to clearing. The UN has called the model "the most important conservation breakthrough of the decade."',
    sourceUrl: 'https://example.com/colombia-amazon',
    sourceName: 'Science Magazine',
    region: 'Latin America',
    country: 'Colombia',
    category: 'Environment',
    tags: ['Amazon', 'deforestation', 'indigenous rights', 'conservation', 'Colombia'],
    publishedAt: '2026-02-16T09:15:00Z',
    imageUrl: 'https://picsum.photos/seed/amazon/800/450',
    positivityScore: 97,
    trending: false,
    featured: false,
    readTime: 5,
  },
  {
    id: '24',
    title: 'Ethiopia\'s "Blue Revolution" Brings Clean Water to 10 Million in Drought-Prone Regions',
    summary: 'Ethiopia\'s national clean water initiative, combining deep borehole drilling, solar pumping, and community management systems, has extended reliable water access to 10 million previously waterless rural residents.',
    content: 'Ethiopia\'s Blue Revolution, a five-year national clean water initiative, has passed its 10-million-beneficiary milestone, delivering reliable, clean water to residents of the country\'s most drought-prone regions. The program combines deep borehole drilling technology that accesses ancient aquifers, solar-powered pumping stations that eliminate dependence on fuel, and an innovative community ownership model where villages manage their own water infrastructure. Water-borne disease rates in program areas have fallen by 78%, and girls who previously spent hours each day fetching water from distant sources are now attending school at record rates. The initiative has been so successful that the World Bank has committed $1.2 billion to expand the model to 12 other water-stressed African nations. Ethiopia\'s Water Minister called it "the beginning of the end of water poverty in Africa."',
    sourceUrl: 'https://example.com/ethiopia-water',
    sourceName: 'Reuters Africa',
    region: 'Africa',
    country: 'Ethiopia',
    category: 'Humanitarian',
    tags: ['clean water', 'Ethiopia', 'Africa', 'development', 'health'],
    publishedAt: '2026-02-15T10:45:00Z',
    imageUrl: 'https://picsum.photos/seed/water2/800/450',
    positivityScore: 97,
    trending: false,
    featured: false,
    readTime: 4,
  },
  {
    id: '25',
    title: 'Copenhagen Becomes World\'s First Zero-Waste City — 3 Years Ahead of Schedule',
    summary: 'Copenhagen has achieved true zero landfill status, with 99.7% of all waste either recycled, composted, or converted to energy — completing its 2030 sustainability pledge a full three years early.',
    content: 'Copenhagen has achieved what urban planners once considered impossible: true zero-waste status, with 99.7% of all municipal waste now recycled, composted, or converted to clean energy through waste-to-energy plants. The milestone, confirmed by independent auditors, was reached three years ahead of the city\'s 2030 target. The achievement required transforming not just waste management infrastructure but citizen behavior, achieved through gamified recycling apps, building-level sorting competitions, and a circular economy incentive program that returns 12% of savings from reduced landfill costs directly to household rates. Copenhagen\'s Amager Bakke waste-to-energy facility — which doubled as an artificial ski slope — processed the final 0.3% of non-recyclable materials while generating electricity for 50,000 homes. Forty-seven cities worldwide have announced plans to replicate the Copenhagen model.',
    sourceUrl: 'https://example.com/copenhagen-zero-waste',
    sourceName: 'Politiken',
    region: 'Europe',
    country: 'Denmark',
    category: 'Environment',
    tags: ['zero waste', 'Copenhagen', 'Denmark', 'recycling', 'sustainability'],
    publishedAt: '2026-02-14T08:00:00Z',
    imageUrl: 'https://picsum.photos/seed/copenhagen/800/450',
    positivityScore: 94,
    trending: false,
    featured: false,
    readTime: 3,
  },
  {
    id: '26',
    title: 'Paralympic Athletes Break 12 World Records at Global Games, Redefining Human Potential',
    summary: 'The 2026 Global Paralympic Games produced a record-breaking 12 new world records across athletics, swimming, and cycling, with viewership surpassing the Olympics for the first time in history.',
    content: 'The 2026 Global Paralympic Games have concluded with 12 new world records shattered across athletics, swimming, and cycling — the most in a single Games in Paralympic history — and a global viewership of 3.1 billion that, for the first time ever, surpassed the Olympics. Athletes including South African sprinter Themba Dlamini, who set a new 100m world record of 10.41 seconds despite a prosthetic limb, captivated audiences worldwide and sparked global conversations about the nature of human ability and perseverance. The record viewership was attributed partly to a new broadcast partnership that streamed all events free worldwide, and to social media coverage that gave athletes unprecedented platforms to share their stories. The International Paralympic Committee reported a 45% surge in youth enrollment in adaptive sports programs in the week following the Games.',
    sourceUrl: 'https://example.com/paralympics',
    sourceName: 'Olympic Channel',
    region: 'Global',
    country: 'International',
    category: 'Sports',
    tags: ['Paralympics', 'sports', 'inspiration', 'inclusion', 'world records'],
    publishedAt: '2026-02-13T17:00:00Z',
    imageUrl: 'https://picsum.photos/seed/paralympics/800/450',
    positivityScore: 95,
    trending: true,
    featured: false,
    readTime: 3,
  },
  {
    id: '27',
    title: 'Free Mental Health App Reaches 50 Million Users, Reducing Anxiety Globally by Measurable Degree',
    summary: '"Calm Path" — a free, evidence-based mental health app developed in partnership with WHO — has reached 50 million active users and demonstrated a statistically significant reduction in population-level anxiety in 15 countries.',
    content: 'The World Health Organization has published results confirming that Calm Path, the free mental health app it co-developed and released in 2023, has generated a statistically measurable reduction in population-level anxiety and depression symptoms across the 15 countries where its use has been most widespread. With 50 million active users — predominantly in low- and middle-income nations where traditional mental health services are scarce — the app provides evidence-based cognitive behavioral therapy exercises, guided meditation, and crisis support in 30 languages. A randomized trial across 40,000 users showed a 31% reduction in PHQ-9 depression scores after eight weeks of regular use. Critically, the app requires no internet connection after initial download, making it accessible in rural and bandwidth-limited settings. WHO Director Dr. Tedros praised it as "perhaps the most cost-effective mental health intervention in history."',
    sourceUrl: 'https://example.com/calm-path',
    sourceName: 'WHO Report',
    region: 'Global',
    country: 'International',
    category: 'Health',
    tags: ['mental health', 'app', 'WHO', 'anxiety', 'wellness'],
    publishedAt: '2026-02-12T11:00:00Z',
    imageUrl: 'https://picsum.photos/seed/mentalhealth/800/450',
    positivityScore: 95,
    trending: false,
    featured: false,
    readTime: 4,
  },
  {
    id: '28',
    title: 'Harlem Music School Produces 3 Grammy Nominees from At-Risk Youth Program',
    summary: 'Harlem\'s Melody Foundation, which provides free classical and contemporary music education to at-risk youth, announced that three of this year\'s Grammy nominees are program alumni — its most celebrated year yet.',
    content: 'The Melody Foundation, a free music education program serving at-risk youth in Harlem, New York, is celebrating an extraordinary milestone: three of this year\'s Grammy Award nominees learned their craft through its after-school programs. Singer-songwriter Maya Okafor, jazz pianist Devin Cruz, and producer collective Sound Architects — all raised in Harlem with limited means — credit the Foundation with giving them their first instruments, their earliest performance opportunities, and the mentors who believed in them. Beyond the Grammy spotlight, the Foundation\'s data shows long-term impact: among its 8,000 alumni, high school graduation rates run at 94% (vs. 70% for the surrounding district), and only 6% have been involved in the criminal justice system (vs. 28% for comparable demographics). Founder Maria Esperanza says the Grammy nominations are wonderful, "but the real story is 8,000 young people who found their voice."',
    sourceUrl: 'https://example.com/harlem-music',
    sourceName: 'New York Times',
    region: 'North America',
    country: 'United States',
    category: 'Arts & Culture',
    tags: ['music', 'youth', 'Grammy', 'education', 'Harlem'],
    publishedAt: '2026-02-11T13:30:00Z',
    imageUrl: 'https://picsum.photos/seed/music/800/450',
    positivityScore: 94,
    trending: false,
    featured: false,
    readTime: 3,
  },
  {
    id: '29',
    title: 'Doctors Eradicate Lymphatic Filariasis from Pacific Island Chain — First Disease Cleared in Region',
    summary: 'A 15-year WHO-led mass drug administration program has achieved the complete eradication of lymphatic filariasis from the Solomon Islands, the first disease ever eliminated from the Pacific Island region.',
    content: 'The Solomon Islands have become the first country in the Pacific Island region to completely eradicate a neglected tropical disease, with WHO confirming the elimination of lymphatic filariasis — a parasitic infection that causes debilitating elephantiasis — following 15 years of systematic mass drug administration. The program, conducted in partnership with local health workers, treated 95% of the population annually for over a decade using a combination of two antiparasitic medications. The final round of surveys found zero active infections across all 60 participating communities. Dr. Emmanuel Nakagawa of the Pacific WHO office called it "a triumph of grassroots public health, delivered by community health workers who walked to every village." The success has been replicated in six neighboring island nations, and experts believe the entire Pacific region could be filariasis-free by 2030.',
    sourceUrl: 'https://example.com/filariasis-eradication',
    sourceName: 'The Lancet',
    region: 'Oceania',
    country: 'Solomon Islands',
    category: 'Health',
    tags: ['disease eradication', 'Pacific', 'public health', 'WHO', 'tropical disease'],
    publishedAt: '2026-02-10T09:00:00Z',
    imageUrl: 'https://picsum.photos/seed/health/800/450',
    positivityScore: 97,
    trending: false,
    featured: false,
    readTime: 4,
  },
  {
    id: '30',
    title: 'Seoul\'s New Hyperloop Metro System Cuts City Commute Times by 65% and Carbon Emissions by Half',
    summary: 'Seoul has launched the world\'s most advanced urban transit network, integrating hyperloop pods with traditional rail to cut average commute times from 55 to 19 minutes while cutting transport emissions by 50%.',
    content: 'Seoul has opened the world\'s most advanced urban transit network, integrating hyperloop technology into its existing metro infrastructure to create a seamless system that has cut average commute times from 55 to just 19 minutes. The 220-kilometer hyperloop network, built over four years in tunnels beneath the existing subway, uses magnetic levitation to propel sealed pods at speeds up to 400 km/h, connecting the city\'s 25 districts in minutes. In the three months since launch, private car usage in Seoul has fallen by 38%, transport-related carbon emissions are down 50%, and road congestion — once among the worst in Asia — has fallen to historically low levels. Property prices in previously remote districts have equalized as commute barriers collapse. Transport Minister Park Ji-won announced plans to extend the network to Incheon and Suwon by 2030, creating a Greater Seoul metropolitan area where no point is more than 30 minutes from the center.',
    sourceUrl: 'https://example.com/seoul-hyperloop',
    sourceName: 'Korea Herald',
    region: 'Asia',
    country: 'South Korea',
    category: 'Science & Tech',
    tags: ['transport', 'hyperloop', 'Seoul', 'innovation', 'sustainability'],
    publishedAt: '2026-02-09T08:30:00Z',
    imageUrl: 'https://picsum.photos/seed/hyperloop/800/450',
    positivityScore: 93,
    trending: true,
    featured: false,
    readTime: 4,
  },
  {
    id: '31',
    title: 'Oman Fishermen Establish Gulf\'s First Community-Run Marine Sanctuary, Fish Stocks Triple',
    summary: 'A fishermen\'s cooperative in the Gulf of Oman voluntarily closed 800 square kilometers to fishing for five years; the result is a marine sanctuary where fish populations have tripled and incomes have doubled.',
    content: 'In a remarkable example of community-led environmental stewardship, a cooperative of 340 Omani fishermen voluntarily closed 800 square kilometers of the most productive fishing grounds in the Gulf of Oman to all commercial fishing for five years. The sacrifice has paid extraordinary dividends: fish biomass in the protected area has tripled, and spillover from the sanctuary into adjacent fishing areas has increased catch rates by 140% for cooperative members — more than doubling their incomes compared to the period before closure. The sanctuary has also attracted whale sharks, dolphins, and dugongs not seen in the region for decades. The Oman Fisheries Authority has formalized the sanctuary under national law, and the cooperative model is being studied by fishing communities across the Arabian Peninsula and Indian Ocean. Lead organizer Ahmed Al-Busaidi said simply: "We fished less, and now we have more than we ever dreamed."',
    sourceUrl: 'https://example.com/oman-sanctuary',
    sourceName: 'Arab News',
    region: 'Middle East',
    country: 'Oman',
    category: 'Environment',
    tags: ['fishing', 'marine conservation', 'Oman', 'community', 'ocean'],
    publishedAt: '2026-02-08T12:00:00Z',
    imageUrl: 'https://picsum.photos/seed/fishing/800/450',
    positivityScore: 96,
    trending: false,
    featured: false,
    readTime: 3,
  },
  {
    id: '32',
    title: 'Bangladesh Girls\' Education Program Raises Female Literacy to 96%, Transforming Rural Communities',
    summary: 'Bangladesh\'s pioneering girls\' secondary education scholarship program has raised female literacy rates to 96% — among the highest in South Asia — producing a generation of women leaders transforming their communities.',
    content: 'Bangladesh has achieved a transformation in female education that economists describe as one of the most powerful development investments ever made. Female literacy, which stood at 28% in 1990, has reached 96% following decades of investment in the Female Secondary School Assistance Program, which provides scholarships, stipends, and bicycles to girls in rural areas to overcome the economic and logistical barriers to education. The impact extends far beyond literacy: the average Bangladeshi woman today has 2.1 children compared to 6.9 in 1980, maternal mortality has fallen by 76%, and women now hold 41% of seats in local government councils. World Bank economists credit women\'s education as the single largest driver of Bangladesh\'s remarkable economic growth from one of Asia\'s poorest nations to lower-middle-income status. The program is now being adapted for implementation in 14 countries across South Asia and sub-Saharan Africa.',
    sourceUrl: 'https://example.com/bangladesh-education',
    sourceName: 'The Daily Star',
    region: 'Asia',
    country: 'Bangladesh',
    category: 'Education',
    tags: ['girls education', 'Bangladesh', 'literacy', 'women', 'development'],
    publishedAt: '2026-02-07T10:00:00Z',
    imageUrl: 'https://picsum.photos/seed/education/800/450',
    positivityScore: 97,
    trending: false,
    featured: false,
    readTime: 4,
  },
  {
    id: '33',
    title: 'CGIAR Scientists Release Drought-Resistant Wheat Variety That Thrives With 60% Less Water',
    summary: 'Agricultural researchers have developed a new wheat variety using advanced gene editing that maintains full yields with 60% less rainfall, offering food security to 1.5 billion people in water-stressed regions.',
    content: 'A team of agricultural scientists at CGIAR\'s International Maize and Wheat Improvement Center has released a new wheat variety that maintains full yields with 60% less water than conventional varieties, using CRISPR gene editing to activate dormant drought-resistance mechanisms found in wild wheat ancestors. Field trials across 30 water-stressed regions in six countries — including parts of sub-Saharan Africa, South Asia, and the Middle East — confirmed that the variety performs consistently in conditions where conventional wheat fails completely. Because the modification involves only wheat\'s own genetic material, the variety has cleared regulatory review in 40 countries as a non-GMO crop. Seed banks are preparing free distribution to 8 million smallholder farmers in the most vulnerable regions, with the goal of reaching 1.5 billion people living in food-insecure, drought-prone areas.',
    sourceUrl: 'https://example.com/drought-wheat',
    sourceName: 'CGIAR',
    region: 'Africa',
    country: 'Ethiopia',
    category: 'Science & Tech',
    tags: ['agriculture', 'drought', 'food security', 'gene editing', 'climate adaptation'],
    publishedAt: '2026-02-06T08:00:00Z',
    imageUrl: 'https://picsum.photos/seed/wheat/800/450',
    positivityScore: 96,
    trending: false,
    featured: false,
    readTime: 4,
  },
  {
    id: '34',
    title: 'Ocean Cleanup Project Removes Record 200,000 Tons of Plastic from Pacific in Single Year',
    summary: 'The Ocean Cleanup\'s expanded fleet of autonomous systems has removed a record 200,000 metric tons of plastic from the Great Pacific Garbage Patch — equivalent to 20,000 garbage trucks — and converted it all into consumer products.',
    content: 'The Ocean Cleanup has announced its most successful year ever, removing a record 200,000 metric tons of plastic from the Great Pacific Garbage Patch — a figure that represents more plastic removed in one year than in the previous five years combined. The achievement was made possible by a new generation of solar-powered autonomous cleanup vessels that use AI to identify and efficiently collect the densest concentrations of debris. Every kilogram of recovered plastic is shipped to shore and processed into recycled materials sold to consumer goods companies, making the operation financially self-sustaining for the first time. Scientific surveys show that plastic concentrations in the cleanup area have fallen by 31% from peak levels. Founder Boyan Slat announced that at the current rate, the Great Pacific Garbage Patch could be reduced by 90% within 15 years, and expanded operations targeting the Indian and Atlantic Oceans are now underway.',
    sourceUrl: 'https://example.com/ocean-cleanup',
    sourceName: 'Ocean Cleanup',
    region: 'Global',
    country: 'International',
    category: 'Environment',
    tags: ['ocean', 'plastic', 'cleanup', 'environment', 'innovation'],
    publishedAt: '2026-02-05T13:00:00Z',
    imageUrl: 'https://picsum.photos/seed/cleanup/800/450',
    positivityScore: 95,
    trending: true,
    featured: false,
    readTime: 4,
  },
  {
    id: '35',
    title: 'German "Silver Coders" Program Sees 10,000 Retirees Launch Tech Startups',
    summary: 'Germany\'s Silver Coders initiative — free coding bootcamps for adults over 60 — has produced 10,000 technology startup founders, proving that innovation has no age limit and generating €2 billion in economic activity.',
    content: 'Germany\'s Silver Coders program, which offers free 12-week coding bootcamps to adults over 60, has reached a milestone: 10,000 program graduates have launched technology startups, generating a combined €2 billion in economic activity and employing over 30,000 people. Many of the most successful startups leverage their founders\' decades of domain expertise — a retired surgeon who built an AI triage tool, a former logistics manager whose route-optimization app is now used by 200 trucking companies, and a retired teacher whose adaptive reading platform has reached 5 million children. The program has expanded to 14 European nations and been praised for countering both ageism in tech and the senior loneliness epidemic. European Commission President Ursula von der Leyen cited Silver Coders as "proof that the best investments in innovation are also investments in human dignity."',
    sourceUrl: 'https://example.com/silver-coders',
    sourceName: 'Der Spiegel',
    region: 'Europe',
    country: 'Germany',
    category: 'Science & Tech',
    tags: ['technology', 'seniors', 'startups', 'Germany', 'inclusion'],
    publishedAt: '2026-02-04T11:00:00Z',
    imageUrl: 'https://picsum.photos/seed/seniors/800/450',
    positivityScore: 93,
    trending: false,
    featured: false,
    readTime: 4,
  },
]

export function getAllArticles(): Article[] {
  return articles
}

export function getFeaturedArticles(): Article[] {
  return articles.filter(a => a.featured).slice(0, 4)
}

export function getTrendingArticles(): Article[] {
  return articles.filter(a => a.trending)
}

export function getArticleById(id: string): Article | undefined {
  return articles.find(a => a.id === id)
}

export function getArticlesByRegion(region: string): Article[] {
  if (region === 'All') return articles
  return articles.filter(a => a.region === region)
}

export function getArticlesByCategory(category: string): Article[] {
  if (category === 'All') return articles
  return articles.filter(a => a.category === category)
}

export function searchArticles(query: string, region?: string, category?: string): Article[] {
  let results = articles

  if (region && region !== 'All') {
    results = results.filter(a => a.region === region)
  }

  if (category && category !== 'All') {
    results = results.filter(a => a.category === category)
  }

  if (query) {
    const q = query.toLowerCase()
    results = results.filter(a =>
      a.title.toLowerCase().includes(q) ||
      a.summary.toLowerCase().includes(q) ||
      a.tags.some(t => t.toLowerCase().includes(q)) ||
      a.country.toLowerCase().includes(q) ||
      a.sourceName.toLowerCase().includes(q)
    )
  }

  return results
}

export function getRelatedArticles(article: Article, limit = 3): Article[] {
  return articles
    .filter(a => a.id !== article.id && (a.category === article.category || a.region === article.region))
    .slice(0, limit)
}

export function getArticlesByIds(ids: string[]): Article[] {
  return articles.filter(a => ids.includes(a.id))
}
