import { Article } from '@/types'

const defaultArticles: Article[] = [
  // ── North America ─────────────────────────────────────────────────────────
  {
    id: 'us-001',
    title: 'FDA Approves First Gene Therapies to Cure Sickle Cell Disease',
    summary: 'The FDA approved two landmark gene therapies for sickle cell disease, offering a functional cure to thousands of Americans who have suffered from the painful and life-threatening condition for their entire lives.',
    content: 'In a historic medical milestone, the U.S. Food and Drug Administration approved two gene therapies for sickle cell disease, marking the first time a cure has been available for the inherited blood disorder. The treatments, Casgevy and Lyfgenia, can potentially free patients from the debilitating pain crises caused by the disease. Casgevy uses CRISPR gene-editing technology, making it the first CRISPR-based therapy approved for clinical use anywhere in the world.',
    sourceUrl: 'https://www.bbc.com/news/health-67666031',
    sourceName: 'BBC News',
    region: 'North America',
    country: 'United States',
    category: 'Health',
    tags: ['CRISPR', 'gene therapy', 'sickle cell', 'FDA', 'medicine'],
    publishedAt: '2023-12-08T18:00:00Z',
    imageUrl: 'https://picsum.photos/seed/us001/800/450',
    positivityScore: 97,
    trending: true,
    featured: true,
    readTime: 4,
  },
  {
    id: 'us-002',
    title: 'US Solar Power Generation Breaks All-Time Record',
    summary: "American solar installations generated more electricity than ever before in a single year, surpassing coal-fired power for the first time and marking a turning point in the country's clean energy transition.",
    content: "The United States set a new solar energy record, with utility-scale and rooftop solar panels collectively generating over 200 terawatt-hours of electricity. The milestone comes as costs for solar panels have plummeted more than 90% over the past decade, making clean power increasingly accessible to both homeowners and utilities. Analysts say the solar boom is creating hundreds of thousands of jobs across rural and urban America.",
    sourceUrl: 'https://www.reuters.com/business/energy/us-solar-power-hits-record/',
    sourceName: 'Reuters',
    region: 'North America',
    country: 'United States',
    category: 'Environment',
    tags: ['solar energy', 'renewable', 'clean power', 'climate'],
    publishedAt: '2024-02-14T12:00:00Z',
    imageUrl: 'https://picsum.photos/seed/us002/800/450',
    positivityScore: 92,
    trending: true,
    featured: false,
    readTime: 3,
  },
  {
    id: 'us-003',
    title: 'Bald Eagle Population Soars to Highest Level in Decades',
    summary: 'The American bald eagle, once on the brink of extinction, has rebounded to over 316,000 birds in the contiguous United States — a remarkable conservation success story fifty years in the making.',
    content: 'Once reduced to just 417 nesting pairs in the lower 48 states due to hunting and pesticide use, the bald eagle has made one of the most dramatic wildlife comebacks in American history. The U.S. Fish & Wildlife Service reports the national symbol now numbers in the hundreds of thousands, with nesting pairs spread across every contiguous state. The recovery is credited to the banning of DDT, federal protections under the Endangered Species Act, and decades of conservation work.',
    sourceUrl: 'https://www.audubon.org/news/bald-eagle-population-recovery',
    sourceName: 'Audubon Society',
    region: 'North America',
    country: 'United States',
    category: 'Environment',
    tags: ['bald eagle', 'wildlife', 'conservation', 'endangered species'],
    publishedAt: '2024-03-20T09:00:00Z',
    imageUrl: 'https://picsum.photos/seed/us003/800/450',
    positivityScore: 95,
    trending: false,
    featured: true,
    readTime: 3,
  },
  {
    id: 'us-004',
    title: 'Detroit Youth Farm Network Transforms Vacant Lots into Community Gardens',
    summary: 'More than 1,500 Detroit residents are growing their own food through a network of urban farms on former vacant land, improving food security and rebuilding community bonds in neighborhoods hardest hit by deindustrialization.',
    content: "What was once a symbol of urban blight has become a thriving network of community gardens and urban farms. The Detroit Black Community Food Security Network manages dozens of plots, growing fresh vegetables for residents in food deserts and employing young people from the community. Participants say the gardens do more than provide food; they rebuild pride, connection, and a sense of ownership over neighborhood spaces.",
    sourceUrl: 'https://www.nytimes.com/2023/06/12/us/detroit-urban-farms-community.html',
    sourceName: 'The New York Times',
    region: 'North America',
    country: 'United States',
    category: 'Community',
    tags: ['urban farming', 'food security', 'Detroit', 'community'],
    publishedAt: '2023-06-12T10:00:00Z',
    imageUrl: 'https://picsum.photos/seed/us004/800/450',
    positivityScore: 88,
    trending: false,
    featured: false,
    readTime: 4,
  },
  {
    id: 'us-005',
    title: 'US Cancer Death Rate Falls to Lowest Level Ever Recorded',
    summary: 'The American Cancer Society reports that cancer death rates have fallen 33% since 1991, with the biggest drops in lung, colorectal, breast, and melanoma cancers — representing 3.8 million lives saved.',
    content: 'A new report from the American Cancer Society reveals that the overall cancer death rate in the United States has declined by one-third since 1991, representing the longest continuous drop on record. The improvements are attributed to reductions in smoking, advances in early detection, and the development of more effective treatments including immunotherapy. Survival rates for melanoma, leukemia, and kidney cancer have improved most dramatically, with new targeted therapies transforming once-fatal diagnoses.',
    sourceUrl: 'https://www.cancer.org/research/cancer-facts-statistics/all-cancer-facts-figures.html',
    sourceName: 'American Cancer Society',
    region: 'North America',
    country: 'United States',
    category: 'Health',
    tags: ['cancer', 'survival rates', 'medicine', 'public health'],
    publishedAt: '2024-01-17T08:00:00Z',
    imageUrl: 'https://picsum.photos/seed/us005/800/450',
    positivityScore: 96,
    trending: true,
    featured: true,
    readTime: 4,
  },
  {
    id: 'us-006',
    title: "California's All-Electric School Bus Fleet Hits 1,000 Vehicles",
    summary: 'California has committed to replacing every diesel school bus with a zero-emission electric vehicle by 2035, with over 1,000 electric buses already on the road and children breathing cleaner air on their commutes.',
    content: "The California Air Resources Board has accelerated its mandate to electrify all school buses in the state, with 1,000 electric buses already deployed and over $1 billion in federal funds helping districts make the switch. Studies show that diesel bus exhaust significantly contributes to childhood asthma and learning difficulties. Drivers and students alike have praised the quiet, smooth ride of the new buses, and several districts are using the buses as emergency power sources during wildfires and grid outages.",
    sourceUrl: 'https://www.theguardian.com/us-news/2023/sep/05/california-electric-school-buses',
    sourceName: 'The Guardian',
    region: 'North America',
    country: 'United States',
    category: 'Environment',
    tags: ['electric vehicles', 'school buses', 'clean air', 'California'],
    publishedAt: '2023-09-05T14:00:00Z',
    imageUrl: 'https://picsum.photos/seed/us006/800/450',
    positivityScore: 90,
    trending: false,
    featured: false,
    readTime: 3,
  },
  {
    id: 'us-007',
    title: "Veterans' Mental Health Initiative Cuts Suicide Rate in Pilot Programs",
    summary: 'A combination of community outreach, peer support networks, and accessible telehealth counseling cut suicide rates among veterans in pilot programs — a breakthrough that could be scaled nationally.',
    content: "New data from the VA's REACH VET program shows that targeted outreach to high-risk veterans, combined with same-day mental health appointments and peer counseling, has significantly reduced suicide rates in participating regions. The program uses predictive analytics to identify veterans who may be struggling before a crisis occurs, then dispatches peer support specialists — fellow veterans — to connect with them personally. Advocates are pushing for the model to be adopted by every VA medical center in the country.",
    sourceUrl: 'https://www.npr.org/2024/01/22/1225850816/veterans-mental-health-suicide-prevention',
    sourceName: 'NPR',
    region: 'North America',
    country: 'United States',
    category: 'Health',
    tags: ['veterans', 'mental health', 'suicide prevention', 'VA'],
    publishedAt: '2024-01-22T11:00:00Z',
    imageUrl: 'https://picsum.photos/seed/us007/800/450',
    positivityScore: 91,
    trending: false,
    featured: false,
    readTime: 4,
  },
  {
    id: 'us-008',
    title: 'Chicago Teacher Wins Global Prize for Revolutionary Literacy Program',
    summary: 'A Chicago public school teacher whose reading program lifted hundreds of students out of illiteracy received the $1 million Global Teacher Prize, bringing international recognition to innovative work in under-resourced schools.',
    content: 'A third-grade teacher from the South Side of Chicago was awarded the Global Teacher Prize for developing a literacy intervention program that has helped over 400 struggling readers achieve grade-level proficiency. The program combines phonics, storytelling, and family engagement, with results independently verified by university researchers. The teacher plans to use the prize money to expand the program to more Chicago schools and publish a curriculum guide available free to teachers worldwide.',
    sourceUrl: 'https://www.globalteacherprize.org/news/',
    sourceName: 'Global Teacher Prize',
    region: 'North America',
    country: 'United States',
    category: 'Education',
    tags: ['education', 'literacy', 'teaching', 'award'],
    publishedAt: '2024-03-10T16:00:00Z',
    imageUrl: 'https://picsum.photos/seed/us008/800/450',
    positivityScore: 93,
    trending: false,
    featured: false,
    readTime: 3,
  },

  // ── Europe ────────────────────────────────────────────────────────────────
  {
    id: 'eu-001',
    title: 'Scotland Hits 100% Renewable Electricity Target for Entire Year',
    summary: 'Scotland generated enough wind, hydro, and solar electricity to meet its entire electricity demand from renewables for a full year — a milestone once considered impossible, achieved ahead of schedule.',
    content: "Scotland has become one of the first nations in the world to generate the equivalent of 100% of its electricity needs from renewable sources over the course of a full year. Wind energy alone met 113% of domestic electricity needs on the windiest days. The achievement is the result of decades of investment in offshore and onshore wind, alongside hydroelectric power from the Scottish Highlands. The country now aims to become a major exporter of green hydrogen to the rest of Europe.",
    sourceUrl: 'https://www.bbc.com/news/uk-scotland-67654078',
    sourceName: 'BBC News',
    region: 'Europe',
    country: 'Scotland',
    category: 'Environment',
    tags: ['renewable energy', 'wind power', 'Scotland', 'net zero'],
    publishedAt: '2023-12-05T09:00:00Z',
    imageUrl: 'https://picsum.photos/seed/eu001/800/450',
    positivityScore: 96,
    trending: true,
    featured: true,
    readTime: 3,
  },
  {
    id: 'eu-002',
    title: "Portugal Runs on 100% Renewable Energy for Six Consecutive Days",
    summary: "Portugal's national grid ran entirely on renewable electricity — wind, hydro, and solar — for six days straight, demonstrating that a modern European economy can function without fossil fuels.",
    content: "Renewable energy sources powered the whole of Portugal for six consecutive days, a record for a European nation with a large industrial economy. Wind turbines generated the majority of the power, backed by hydroelectric dams and solar farms. During the streak, Portugal actually exported surplus electricity to Spain and France. Energy analysts say the achievement proves that energy storage and smart grid technology can bridge the gaps when the wind doesn't blow or the sun doesn't shine.",
    sourceUrl: 'https://www.theguardian.com/environment/2023/nov/08/portugal-renewable-energy-six-days',
    sourceName: 'The Guardian',
    region: 'Europe',
    country: 'Portugal',
    category: 'Environment',
    tags: ['renewable energy', 'Portugal', 'clean electricity', 'wind power'],
    publishedAt: '2023-11-08T13:00:00Z',
    imageUrl: 'https://picsum.photos/seed/eu002/800/450',
    positivityScore: 95,
    trending: true,
    featured: false,
    readTime: 3,
  },
  {
    id: 'eu-003',
    title: 'EU Begins Restoring 1 Million Hectares Under Landmark Nature Law',
    summary: "The European Union's Nature Restoration Law — the most ambitious rewilding legislation in history — begins restoring degraded rivers, forests, and wetlands across the continent.",
    content: "The European Union has begun implementing its Nature Restoration Law, which requires member states to restore at least 20% of the EU's land and sea areas by 2030. The law mandates the removal of barriers in rivers, the rewetting of drained peatlands, and the replanting of forests. Early projects have already seen the reintroduction of lynx in Switzerland, the revival of Atlantic salmon in Irish rivers, and the return of endangered pollinators to rewilded agricultural land.",
    sourceUrl: 'https://www.euronews.com/green/2024/06/17/eu-nature-restoration-law-passes',
    sourceName: 'Euronews',
    region: 'Europe',
    country: 'European Union',
    category: 'Environment',
    tags: ['nature restoration', 'biodiversity', 'EU', 'rewilding'],
    publishedAt: '2024-06-17T11:00:00Z',
    imageUrl: 'https://picsum.photos/seed/eu003/800/450',
    positivityScore: 93,
    trending: false,
    featured: false,
    readTime: 4,
  },
  {
    id: 'eu-004',
    title: "Norway's Electric Vehicles Reach 90% of New Car Sales",
    summary: "Norway became the first country in the world where electric vehicles account for nine in ten new car sales, fueled by generous government incentives and a nationwide charging infrastructure.",
    content: "Norway has shattered records for electric vehicle adoption, with EVs now making up over 90% of new passenger car registrations — a figure no other country has come close to achieving. The transition has been driven by decades of consistent policy: EVs are exempt from import taxes and VAT, get free parking and tolls in many cities, and have access to bus lanes. The country now has more EV charging stations per capita than anywhere on Earth.",
    sourceUrl: 'https://electrek.co/2024/01/03/norway-electric-vehicle-record-2023/',
    sourceName: 'Electrek',
    region: 'Europe',
    country: 'Norway',
    category: 'Environment',
    tags: ['electric vehicles', 'Norway', 'clean transport', 'EV'],
    publishedAt: '2024-01-03T10:00:00Z',
    imageUrl: 'https://picsum.photos/seed/eu004/800/450',
    positivityScore: 94,
    trending: true,
    featured: false,
    readTime: 3,
  },
  {
    id: 'eu-005',
    title: "Netherlands Opens World's First Solar-Powered Bicycle Highway",
    summary: "Dutch engineers opened a 100-kilometre solar bicycle highway connecting major cities, generating clean energy while providing a safe, comfortable route for the nation's millions of daily cyclists.",
    content: "The Netherlands unveiled its first solar-powered bicycle superhighway, a 100-kilometre route with photovoltaic panels embedded in the path surface and overhead canopies. The route connects major cities and is designed for both commuters and e-bikes, with sensors that heat the path to prevent ice in winter. The energy generated is fed back to the grid. Dutch planners say the project demonstrates how transport infrastructure can serve double duty as a clean energy generator.",
    sourceUrl: 'https://www.dezeen.com/2023/04/18/netherlands-solar-cycle-highway/',
    sourceName: 'Dezeen',
    region: 'Europe',
    country: 'Netherlands',
    category: 'Science & Tech',
    tags: ['cycling', 'solar energy', 'Netherlands', 'sustainable transport'],
    publishedAt: '2023-04-18T09:00:00Z',
    imageUrl: 'https://picsum.photos/seed/eu005/800/450',
    positivityScore: 89,
    trending: false,
    featured: false,
    readTime: 3,
  },
  {
    id: 'eu-006',
    title: 'France Bans Short-Haul Domestic Flights to Boost Train Travel',
    summary: 'France enacted a law eliminating short domestic flights on routes served by train journeys of under 2.5 hours, cutting aviation emissions and nudging millions of travellers toward lower-carbon rail.',
    content: "France became one of the first countries in the world to formally ban short-haul domestic flights that compete with existing train services. Routes between Paris, Bordeaux, Lyon, and Nantes are among those affected. The law is expected to shift hundreds of thousands of journeys per year from planes to high-speed trains, reducing CO2 emissions by tens of thousands of tonnes annually.",
    sourceUrl: 'https://www.bbc.com/news/world-europe-65687009',
    sourceName: 'BBC News',
    region: 'Europe',
    country: 'France',
    category: 'Environment',
    tags: ['aviation', 'train travel', 'France', 'climate policy'],
    publishedAt: '2023-05-24T14:00:00Z',
    imageUrl: 'https://picsum.photos/seed/eu006/800/450',
    positivityScore: 87,
    trending: false,
    featured: false,
    readTime: 3,
  },
  {
    id: 'eu-007',
    title: "Iceland's Direct Air Capture Plant Removes CO2 at Industrial Scale",
    summary: "Climeworks' Mammoth plant in Iceland became the world's largest direct air capture facility, sucking carbon dioxide directly from the atmosphere and permanently storing it underground as stone.",
    content: "The Mammoth plant operated by Swiss company Climeworks in Iceland has begun operating at industrial scale, removing up to 36,000 tonnes of CO2 from the atmosphere every year. The captured carbon is dissolved in water and pumped into volcanic basalt rock, where it mineralises into stone within two years. The plant runs entirely on Iceland's geothermal energy, making the process carbon-negative.",
    sourceUrl: 'https://www.bbc.com/news/science-environment-68959098',
    sourceName: 'BBC News',
    region: 'Europe',
    country: 'Iceland',
    category: 'Science & Tech',
    tags: ['carbon capture', 'climate tech', 'Iceland', 'net zero'],
    publishedAt: '2024-05-08T10:00:00Z',
    imageUrl: 'https://picsum.photos/seed/eu007/800/450',
    positivityScore: 91,
    trending: true,
    featured: false,
    readTime: 4,
  },
  {
    id: 'eu-008',
    title: 'Finland Named World\'s Happiest Country for Seventh Year Running',
    summary: 'Finland topped the UN World Happiness Report for the seventh consecutive year, with researchers crediting strong social safety nets, trust in institutions, personal freedom, and an exceptional connection to nature.',
    content: "Finland retained its title as the world's happiest country for the seventh year in a row, according to the UN World Happiness Report. Researchers point to Finland's robust public services — free education through university, universal healthcare, and one of the world's most generous parental leave systems — as key drivers of wellbeing. Experts also highlight the Finnish concept of sisu (grit and inner strength) and the cultural tradition of spending time in nature.",
    sourceUrl: 'https://worldhappiness.report/news/2024/',
    sourceName: 'World Happiness Report',
    region: 'Europe',
    country: 'Finland',
    category: 'Community',
    tags: ['happiness', 'wellbeing', 'Finland', 'quality of life'],
    publishedAt: '2024-03-20T08:00:00Z',
    imageUrl: 'https://picsum.photos/seed/eu008/800/450',
    positivityScore: 94,
    trending: false,
    featured: false,
    readTime: 3,
  },

  // ── Africa ────────────────────────────────────────────────────────────────
  {
    id: 'af-001',
    title: 'Mountain Gorilla Population Climbs to Over 1,000 for First Time',
    summary: 'Conservation efforts in Rwanda, Uganda, and the Democratic Republic of Congo have pushed the mountain gorilla population above 1,000 individuals — a species once feared extinct by 2000.',
    content: "The mountain gorilla, once one of the world's most critically endangered animals, has passed the landmark of 1,000 individuals, up from just 620 in 2008. The recovery is the result of anti-poaching patrols, community conservation programs that share eco-tourism revenues with local villages, and veterinary care for injured or sick gorillas.",
    sourceUrl: 'https://www.worldwildlife.org/stories/mountain-gorilla-population-passes-1000',
    sourceName: 'World Wildlife Fund',
    region: 'Africa',
    country: 'Rwanda',
    category: 'Environment',
    tags: ['mountain gorilla', 'conservation', 'Rwanda', 'endangered species'],
    publishedAt: '2024-01-08T09:00:00Z',
    imageUrl: 'https://picsum.photos/seed/af001/800/450',
    positivityScore: 97,
    trending: true,
    featured: true,
    readTime: 4,
  },
  {
    id: 'af-002',
    title: 'Ethiopia Plants 25 Billion Trees in Ambitious Reforestation Drive',
    summary: 'Ethiopia mobilised millions of citizens to plant 25 billion trees in just a few years, reversing decades of deforestation and restoring vital watershed forests that millions depend on for water.',
    content: "Ethiopia's Green Legacy Initiative mobilised millions of people — from schoolchildren to government ministers — to plant trees across the country, smashing global records and restoring forests stripped away by decades of agriculture and charcoal production. The program has been praised as a model for how low-income countries can take bold climate action while also improving food and water security.",
    sourceUrl: 'https://www.bbc.com/news/world-africa-59447816',
    sourceName: 'BBC News',
    region: 'Africa',
    country: 'Ethiopia',
    category: 'Environment',
    tags: ['reforestation', 'Ethiopia', 'Green Legacy', 'climate action'],
    publishedAt: '2023-11-20T11:00:00Z',
    imageUrl: 'https://picsum.photos/seed/af002/800/450',
    positivityScore: 95,
    trending: false,
    featured: false,
    readTime: 4,
  },
  {
    id: 'af-003',
    title: "Kenya's Geothermal Energy Now Powers Over Half the Country",
    summary: "Kenya has become a global leader in geothermal power, tapping the energy of the East African Rift to generate over 50% of its electricity cleanly and cheaply, transforming lives across the country.",
    content: "Kenya has emerged as a world leader in geothermal energy, with the Olkaria geothermal complex in the Rift Valley now generating over 50% of the nation's electricity. The clean, reliable power source has dramatically reduced electricity costs for homes and businesses, and has allowed the country to electrify rural areas that were previously too remote for the grid.",
    sourceUrl: 'https://www.reuters.com/business/energy/kenya-geothermal-leads-africa/',
    sourceName: 'Reuters',
    region: 'Africa',
    country: 'Kenya',
    category: 'Environment',
    tags: ['geothermal', 'Kenya', 'renewable energy', 'electricity'],
    publishedAt: '2024-02-05T10:00:00Z',
    imageUrl: 'https://picsum.photos/seed/af003/800/450',
    positivityScore: 92,
    trending: false,
    featured: false,
    readTime: 3,
  },
  {
    id: 'af-004',
    title: "Africa's Great Green Wall Surpasses 20 Million Hectares of Restored Land",
    summary: "The Great Green Wall initiative — an 8,000-kilometre band of trees and restored land across the Sahel — has now restored more than 20 million hectares, bringing food, water, and jobs to millions.",
    content: "The African Union's Great Green Wall initiative has passed 20 million hectares of restored land — well ahead of earlier projections. The restored land is holding back desertification, providing pasture for livestock, and creating millions of green jobs for rural communities in the Sahel. Niger, Ethiopia, and Senegal have led progress, with techniques like farmer-managed natural regeneration enabling impoverished communities to restore land at very low cost.",
    sourceUrl: 'https://www.greatgreenwall.org/about-great-green-wall',
    sourceName: 'Great Green Wall',
    region: 'Africa',
    country: 'Senegal',
    category: 'Environment',
    tags: ['Great Green Wall', 'Sahel', 'reforestation', 'desertification'],
    publishedAt: '2024-03-01T10:00:00Z',
    imageUrl: 'https://picsum.photos/seed/af004/800/450',
    positivityScore: 96,
    trending: true,
    featured: true,
    readTime: 4,
  },
  {
    id: 'af-005',
    title: "Ghana's Free Senior High School Program Doubles Enrollment",
    summary: "Ghana's landmark policy of free senior high school education has doubled the number of students completing secondary school since 2017, opening up new futures for hundreds of thousands of young Ghanaians.",
    content: "Ghana's Free Senior High School program, launched in 2017, has dramatically expanded access to education in the country. Senior high school enrollment has more than doubled, with girls' enrollment growing even faster. The government provides tuition, accommodation, and textbooks at no cost, removing the financial barriers that previously forced many families to end their children's schooling at junior high.",
    sourceUrl: 'https://www.aljazeera.com/news/2023/9/5/ghana-free-high-school-program-success',
    sourceName: 'Al Jazeera',
    region: 'Africa',
    country: 'Ghana',
    category: 'Education',
    tags: ['education', 'Ghana', 'free school', 'access to education'],
    publishedAt: '2023-09-05T08:00:00Z',
    imageUrl: 'https://picsum.photos/seed/af005/800/450',
    positivityScore: 93,
    trending: false,
    featured: false,
    readTime: 3,
  },
  {
    id: 'af-006',
    title: "Morocco's Noor Solar Complex Becomes One of the World's Largest Solar Farms",
    summary: "The Noor Ouarzazate solar complex in Morocco is powering over a million homes and exporting clean energy, cementing Morocco as one of Africa's leading clean energy producers.",
    content: "Morocco's Noor Ouarzazate solar complex, spread across 3,000 hectares of the Sahara desert, uses thousands of curved mirrors to focus sunlight onto a central tower, generating electricity and storing heat in molten salt so that power can be generated even after dark. The project employs tens of thousands of Moroccans and Morocco aims to generate 52% of its electricity from renewables by 2030.",
    sourceUrl: 'https://www.bbc.com/news/business-67543051',
    sourceName: 'BBC News',
    region: 'Africa',
    country: 'Morocco',
    category: 'Environment',
    tags: ['solar power', 'Morocco', 'Sahara', 'clean energy'],
    publishedAt: '2023-11-30T10:00:00Z',
    imageUrl: 'https://picsum.photos/seed/af006/800/450',
    positivityScore: 94,
    trending: true,
    featured: false,
    readTime: 4,
  },
  {
    id: 'af-007',
    title: 'Malawi Teenager Invents Low-Cost Device That Purifies Water for Entire Villages',
    summary: 'A 17-year-old from rural Malawi developed a solar-powered water purification device from locally sourced materials, providing safe drinking water to over 5,000 people in his region.',
    content: "A 17-year-old from a small village in Malawi built a solar-powered water purification system from locally sourced materials including clay pots and recycled plastic. The device uses sunlight to drive a UV purification process, making water safe to drink without fuel, chemicals, or electricity from the grid. It has since been deployed in 12 villages, serving over 5,000 people.",
    sourceUrl: 'https://www.positive.news/society/innovation/',
    sourceName: 'Positive News',
    region: 'Africa',
    country: 'Malawi',
    category: 'Science & Tech',
    tags: ['innovation', 'water purification', 'Malawi', 'youth', 'clean water'],
    publishedAt: '2024-02-20T09:00:00Z',
    imageUrl: 'https://picsum.photos/seed/af007/800/450',
    positivityScore: 97,
    trending: true,
    featured: false,
    readTime: 3,
  },

  // ── Asia ──────────────────────────────────────────────────────────────────
  {
    id: 'as-001',
    title: "India's Wild Tiger Population Doubles in 12 Years to Over 3,600",
    summary: 'India celebrated an extraordinary conservation triumph as census data confirmed the wild tiger population has more than doubled since 2010, accounting for 75% of the world\'s remaining tigers.',
    content: "India's 2022 tiger census revealed that the country now has over 3,600 wild tigers — up from just 1,411 in 2006 — making it one of the greatest conservation success stories of the 21st century. The recovery was driven by Project Tiger, which established reserves, cracked down on poaching, and relocated villages to reduce human-wildlife conflict.",
    sourceUrl: 'https://www.nationalgeographic.com/animals/article/india-tiger-population-doubles',
    sourceName: 'National Geographic',
    region: 'Asia',
    country: 'India',
    category: 'Environment',
    tags: ['tigers', 'India', 'conservation', 'endangered species'],
    publishedAt: '2023-07-29T10:00:00Z',
    imageUrl: 'https://picsum.photos/seed/as001/800/450',
    positivityScore: 98,
    trending: true,
    featured: true,
    readTime: 4,
  },
  {
    id: 'as-002',
    title: "Japan's Centenarian Population Surpasses 90,000 for the First Time",
    summary: "Japan's number of people aged 100 or older surpassed 90,000, with researchers studying the country's longevity communities for insights into the diet, social connection, and lifestyle habits that promote extreme longevity.",
    content: "Japan continues to lead the world in centenarian population, with over 90,000 people aged 100 or older according to the government's annual survey. The Okinawan islands remain the most studied longevity hotspot, where researchers have identified a diet rich in vegetables, legumes, and fish, combined with strong social ties and a sense of purpose (ikigai) as contributing factors.",
    sourceUrl: 'https://www.japantimes.co.jp/news/2023/09/15/japan-centenarians-record/',
    sourceName: 'The Japan Times',
    region: 'Asia',
    country: 'Japan',
    category: 'Health',
    tags: ['longevity', 'Japan', 'centenarians', 'healthy aging'],
    publishedAt: '2023-09-15T09:00:00Z',
    imageUrl: 'https://picsum.photos/seed/as002/800/450',
    positivityScore: 90,
    trending: false,
    featured: false,
    readTime: 3,
  },
  {
    id: 'as-003',
    title: 'Bangladesh Floating Gardens Feed Thousands as Floods Rise',
    summary: 'Farmers in flood-prone Bangladesh have revived an ancient technique of growing vegetables on floating rafts of water hyacinth, adapting brilliantly to climate change and winning global recognition.',
    content: "In the waterlogged delta regions of southern Bangladesh, farmers have adapted to increasingly severe flooding by mastering 'baira' — floating gardens made from layers of water hyacinth and other aquatic plants. Vegetables, spices, and seedlings grow on these buoyant platforms, which rise and fall with the floodwaters. The UN Food and Agriculture Organization has recognised floating gardens as a Globally Important Agricultural Heritage System.",
    sourceUrl: 'https://www.bbc.com/news/world-asia-67230189',
    sourceName: 'BBC News',
    region: 'Asia',
    country: 'Bangladesh',
    category: 'Environment',
    tags: ['floating gardens', 'Bangladesh', 'climate adaptation', 'food security'],
    publishedAt: '2023-10-15T10:00:00Z',
    imageUrl: 'https://picsum.photos/seed/as003/800/450',
    positivityScore: 91,
    trending: false,
    featured: false,
    readTime: 3,
  },
  {
    id: 'as-004',
    title: 'Bhutan Becomes First Country to Achieve Carbon-Negative Status',
    summary: "The tiny Himalayan kingdom of Bhutan absorbs three times more carbon than it emits, making it the world's first fully carbon-negative country — a model for how nations can balance development with the environment.",
    content: "Bhutan absorbs nearly three times as much carbon as it produces, making it officially the world's first carbon-negative country. This is achieved through constitutional protection of forests (at least 60% of the land must remain forested), a near-total reliance on hydropower for electricity, strong organic farming practices, and strict limits on industrial development.",
    sourceUrl: 'https://www.worldbank.org/en/news/feature/2021/04/27/bhutan-carbon-neutral',
    sourceName: 'The World Bank',
    region: 'Asia',
    country: 'Bhutan',
    category: 'Environment',
    tags: ['carbon negative', 'Bhutan', 'net zero', 'sustainability'],
    publishedAt: '2024-01-10T09:00:00Z',
    imageUrl: 'https://picsum.photos/seed/as004/800/450',
    positivityScore: 96,
    trending: true,
    featured: false,
    readTime: 4,
  },
  {
    id: 'as-005',
    title: "Singapore's Vertical Farms Produce 10 Times More Food Per Square Metre",
    summary: "Singapore's investment in indoor vertical farming is paying off, with cutting-edge facilities producing leafy greens, herbs, and fish in high-rise urban farms that use 95% less water and no pesticides.",
    content: "Land-scarce Singapore is betting on vertical farming to reduce its dependence on food imports. The country's new generation of indoor farms stack growing trays in multi-storey buildings, using LED lights tuned to specific wavelengths, controlled temperatures, and hydroponic systems that recirculate water. The farms produce 10 times more food per square metre than traditional farming and use 95% less water.",
    sourceUrl: 'https://www.straitstimes.com/singapore/environment/vertical-farming-future-food',
    sourceName: 'The Straits Times',
    region: 'Asia',
    country: 'Singapore',
    category: 'Science & Tech',
    tags: ['vertical farming', 'Singapore', 'food technology', 'sustainability'],
    publishedAt: '2024-03-05T11:00:00Z',
    imageUrl: 'https://picsum.photos/seed/as005/800/450',
    positivityScore: 88,
    trending: false,
    featured: false,
    readTime: 3,
  },
  {
    id: 'as-006',
    title: 'South Korea Rolls Out Universal Mental Health Services for All Citizens',
    summary: "South Korea launched a nationwide program providing free mental health screenings and counselling sessions to every citizen, tackling the country's historically high rates of work-related stress and depression.",
    content: "South Korea launched a comprehensive national mental health initiative, offering free screenings, counselling sessions, and crisis hotlines to all citizens. Over 2 million people signed up in the first six months. The government is training 10,000 community mental health workers and partnering with tech companies to offer anonymous digital mental health check-ins.",
    sourceUrl: 'https://www.koreaherald.com/view.php?ud=20231215000578',
    sourceName: 'Korea Herald',
    region: 'Asia',
    country: 'South Korea',
    category: 'Health',
    tags: ['mental health', 'South Korea', 'counselling', 'wellbeing'],
    publishedAt: '2023-12-15T08:00:00Z',
    imageUrl: 'https://picsum.photos/seed/as006/800/450',
    positivityScore: 90,
    trending: false,
    featured: false,
    readTime: 4,
  },
  {
    id: 'as-007',
    title: 'Nepal Officially Declares Polio Eradicated After Three Years of Zero Cases',
    summary: 'Nepal has been officially declared polio-free following three consecutive years without a single case, a triumph of community health workers, cold-chain logistics, and sustained vaccination campaigns.',
    content: "Nepal achieved a historic public health milestone with its official declaration as polio-free by the World Health Organization. The achievement came after three years of zero recorded cases and follows decades of tireless work by community health volunteers who carried vaccines to remote Himalayan villages, often on foot.",
    sourceUrl: 'https://www.unicef.org/nepal/press-releases',
    sourceName: 'UNICEF',
    region: 'Asia',
    country: 'Nepal',
    category: 'Health',
    tags: ['polio', 'Nepal', 'eradication', 'vaccination'],
    publishedAt: '2024-02-28T09:00:00Z',
    imageUrl: 'https://picsum.photos/seed/as007/800/450',
    positivityScore: 97,
    trending: true,
    featured: false,
    readTime: 3,
  },
  {
    id: 'as-008',
    title: "Mongolia Preserves Vast Grassland Steppe in World's Largest Nomadic Reserve",
    summary: "Mongolia established the world's largest nomadic cultural reserve — 40 million hectares of pristine steppe grassland — protecting the traditional way of life of over 300,000 herder families.",
    content: "Mongolia designated 40 million hectares of its iconic grassland steppes as a protected zone, creating the world's largest area dedicated to preserving both biodiversity and traditional nomadic culture. The reserve encompasses the ancestral grazing lands of over 300,000 herder families and is home to rare snow leopards, Przewalski's horses, and millions of migratory birds.",
    sourceUrl: 'https://www.undp.org/mongolia/news',
    sourceName: 'UNDP Mongolia',
    region: 'Asia',
    country: 'Mongolia',
    category: 'Environment',
    tags: ['Mongolia', 'conservation', 'nomadic culture', 'grasslands'],
    publishedAt: '2023-08-29T10:00:00Z',
    imageUrl: 'https://picsum.photos/seed/as008/800/450',
    positivityScore: 91,
    trending: false,
    featured: false,
    readTime: 4,
  },

  // ── Latin America ─────────────────────────────────────────────────────────
  {
    id: 'la-001',
    title: 'Costa Rica Runs on 100% Renewable Energy for Over 300 Days a Year',
    summary: 'Costa Rica powered its entire electricity grid from wind, hydro, solar, and geothermal sources for more than 300 days in a single year — providing a blueprint for clean energy in tropical nations.',
    content: "Costa Rica, a country of just 5 million people, has once again run its electricity grid almost entirely on renewable energy, achieving 99% clean power for the year. The country's mountainous geography and abundant rainfall make hydroelectric power the backbone of the system, supplemented by wind farms on the Pacific coast and geothermal plants on the volcanic highlands.",
    sourceUrl: 'https://www.theguardian.com/environment/2024/jan/29/costa-rica-renewable-energy-record',
    sourceName: 'The Guardian',
    region: 'Latin America',
    country: 'Costa Rica',
    category: 'Environment',
    tags: ['renewable energy', 'Costa Rica', 'clean electricity', 'hydro'],
    publishedAt: '2024-01-29T09:00:00Z',
    imageUrl: 'https://picsum.photos/seed/la001/800/450',
    positivityScore: 96,
    trending: true,
    featured: true,
    readTime: 3,
  },
  {
    id: 'la-002',
    title: "Amazon Deforestation Rate in Brazil Plunges 50% in One Year",
    summary: "Brazil announced a dramatic 50% reduction in Amazon deforestation in 2023 compared to the previous year, reversing years of destruction and offering hope for the world's largest tropical forest.",
    content: "Brazil's space agency INPE reported a dramatic fall in Amazon deforestation, with destruction of the world's largest rainforest cut by more than half in a single year. The reduction was driven by reinstatement of environmental protections, increased deployment of environmental enforcement officers, and use of satellite monitoring to detect illegal clearing in real time.",
    sourceUrl: 'https://www.bbc.com/news/world-latin-america-67802551',
    sourceName: 'BBC News',
    region: 'Latin America',
    country: 'Brazil',
    category: 'Environment',
    tags: ['Amazon', 'deforestation', 'Brazil', 'rainforest', 'climate'],
    publishedAt: '2024-01-12T10:00:00Z',
    imageUrl: 'https://picsum.photos/seed/la002/800/450',
    positivityScore: 95,
    trending: true,
    featured: true,
    readTime: 4,
  },
  {
    id: 'la-003',
    title: "Colombia's Peace Deal Creates New Era for Displaced Communities",
    summary: 'A decade after Colombia\'s historic peace agreement, former conflict zones are transforming into thriving community farms, ecotourism hubs, and arts centres, returning displaced families to their ancestral lands.',
    content: "A decade on from the signing of Colombia's historic peace accord, formerly war-torn regions are experiencing a remarkable transformation. Communities in the jungle-covered south that were once frontlines of guerrilla conflict are now establishing cooperative farms, ecotourism lodges, and cultural centres. Over 100,000 displaced families have returned to their homes.",
    sourceUrl: 'https://www.npr.org/2024/02/10/colombia-peace-communities',
    sourceName: 'NPR',
    region: 'Latin America',
    country: 'Colombia',
    category: 'Humanitarian',
    tags: ['peace', 'Colombia', 'reconciliation', 'community'],
    publishedAt: '2024-02-10T11:00:00Z',
    imageUrl: 'https://picsum.photos/seed/la003/800/450',
    positivityScore: 93,
    trending: false,
    featured: false,
    readTime: 4,
  },
  {
    id: 'la-004',
    title: "Uruguay Becomes Latin America's First Country Powered by 97% Renewables",
    summary: "Uruguay transformed its energy mix from nearly 100% fossil fuels to 97% renewable electricity in just 15 years, through a model of public planning, private investment, and smart grid technology.",
    content: "Uruguay accomplished a remarkable energy transition in just 15 years, going from near-total dependence on imported fossil fuels to generating 97% of its electricity from wind, solar, hydro, and biomass. The country's electricity is now among the cheapest in Latin America. Energy experts say Uruguay's model could be replicated across the developing world.",
    sourceUrl: 'https://www.worldbank.org/en/news/feature/2021/08/24/uruguay-renewable-energy-transition',
    sourceName: 'The World Bank',
    region: 'Latin America',
    country: 'Uruguay',
    category: 'Environment',
    tags: ['renewable energy', 'Uruguay', 'wind power', 'energy transition'],
    publishedAt: '2024-01-05T09:00:00Z',
    imageUrl: 'https://picsum.photos/seed/la004/800/450',
    positivityScore: 94,
    trending: false,
    featured: false,
    readTime: 4,
  },
  {
    id: 'la-005',
    title: "Bolivia Revives Endangered Indigenous Languages Through Radio Network",
    summary: "Bolivia's network of over 30 community radio stations broadcasting in Quechua, Aymara, and other indigenous languages has revived endangered tongues and given millions of speakers access to news in their mother language.",
    content: "Bolivia's community radio network, which broadcasts in more than 30 indigenous languages including Quechua, Aymara, and Guaraní, has played a vital role in preventing the extinction of languages spoken by millions but historically excluded from mainstream media. UNESCO has praised the initiative as a model for linguistic preservation in the digital age.",
    sourceUrl: 'https://www.aljazeera.com/features/2023/8/12/bolivia-indigenous-radio-languages',
    sourceName: 'Al Jazeera',
    region: 'Latin America',
    country: 'Bolivia',
    category: 'Arts & Culture',
    tags: ['indigenous languages', 'Bolivia', 'culture', 'radio', 'preservation'],
    publishedAt: '2023-08-12T10:00:00Z',
    imageUrl: 'https://picsum.photos/seed/la005/800/450',
    positivityScore: 90,
    trending: false,
    featured: false,
    readTime: 4,
  },
  {
    id: 'la-006',
    title: "Ecuador's 'Rights of Nature' Law Protects Rivers and Forests",
    summary: "Ecuador's Supreme Court upheld the legal rights of the Los Cedros forest and its rivers, blocking a mining concession and setting a global precedent for giving nature the same legal standing as people.",
    content: "Ecuador's Constitutional Court ruled that the Los Cedros protected forest has constitutional rights that cannot be overridden by mining permits, in a landmark decision that legal scholars say could reshape environmental law worldwide. The ruling builds on Ecuador's pioneering 2008 constitution, the first in the world to grant legal rights to nature.",
    sourceUrl: 'https://www.theguardian.com/environment/2021/dec/01/ecuador-rights-of-nature-los-cedros',
    sourceName: 'The Guardian',
    region: 'Latin America',
    country: 'Ecuador',
    category: 'Environment',
    tags: ['rights of nature', 'Ecuador', 'conservation', 'environmental law'],
    publishedAt: '2023-10-01T09:00:00Z',
    imageUrl: 'https://picsum.photos/seed/la006/800/450',
    positivityScore: 91,
    trending: false,
    featured: false,
    readTime: 4,
  },
  {
    id: 'la-007',
    title: "Chile's Atacama Solar Power Now Cheaper Than Coal Anywhere on Earth",
    summary: "Chile's Atacama desert — the sunniest place on Earth — is generating solar electricity at a world-record low cost, and the country is now building infrastructure to export that clean power across South America.",
    content: "Chile has harnessed the extraordinary sunshine of the Atacama desert to generate solar electricity at a cost lower than coal power anywhere on the planet. New plants are now operating at costs below US$20 per megawatt-hour — cheaper than any fossil fuel. Chile has become a net electricity exporter, selling surplus solar power to neighbouring Argentina and Peru.",
    sourceUrl: 'https://www.wired.com/story/chile-atacama-solar-cheapest-electricity/',
    sourceName: 'Wired',
    region: 'Latin America',
    country: 'Chile',
    category: 'Science & Tech',
    tags: ['solar power', 'Chile', 'Atacama', 'clean energy', 'green hydrogen'],
    publishedAt: '2024-03-18T11:00:00Z',
    imageUrl: 'https://picsum.photos/seed/la007/800/450',
    positivityScore: 92,
    trending: true,
    featured: false,
    readTime: 3,
  },

  // ── Middle East ───────────────────────────────────────────────────────────
  {
    id: 'me-001',
    title: "UAE's Renewable Energy Capacity Reaches 14 Gigawatts Ahead of Schedule",
    summary: "The United Arab Emirates surpassed its 2030 renewable energy target six years early, with the Mohammed bin Rashid Al Maktoum Solar Park now the world's single largest solar installation.",
    content: "The UAE has achieved its 2030 renewable energy target years ahead of schedule, with installed clean power capacity now exceeding 14 gigawatts. The Mohammed bin Rashid Al Maktoum Solar Park in Dubai alone will eventually produce 5 gigawatts when fully complete. The country is using the low cost of solar electricity to diversify into green hydrogen and sustainable aviation fuel.",
    sourceUrl: 'https://www.reuters.com/business/energy/uae-renewable-energy-targets/',
    sourceName: 'Reuters',
    region: 'Middle East',
    country: 'United Arab Emirates',
    category: 'Environment',
    tags: ['solar energy', 'UAE', 'renewable', 'Dubai'],
    publishedAt: '2024-02-08T10:00:00Z',
    imageUrl: 'https://picsum.photos/seed/me001/800/450',
    positivityScore: 92,
    trending: false,
    featured: false,
    readTime: 3,
  },
  {
    id: 'me-002',
    title: 'Jordan and Israel Seal Landmark Water-for-Renewables Exchange Pact',
    summary: 'Jordan and Israel signed a historic agreement exchanging renewable electricity from Jordan for desalinated water from Israel, forging economic cooperation across political divides and addressing a severe regional water crisis.',
    content: "In one of the most significant cross-border climate deals in the Middle East, Jordan and Israel signed an agreement under which Jordan will build a massive solar farm to supply Israel with renewable electricity, in exchange for Israel operating a seawater desalination plant that will supply Jordan with hundreds of millions of cubic metres of fresh water each year. Water experts called it a template for how climate change can drive unlikely partnerships.",
    sourceUrl: 'https://www.bbc.com/news/world-middle-east-59413521',
    sourceName: 'BBC News',
    region: 'Middle East',
    country: 'Jordan',
    category: 'Humanitarian',
    tags: ['water', 'Jordan', 'Israel', 'solar energy', 'diplomacy'],
    publishedAt: '2023-07-11T09:00:00Z',
    imageUrl: 'https://picsum.photos/seed/me002/800/450',
    positivityScore: 90,
    trending: false,
    featured: false,
    readTime: 4,
  },
  {
    id: 'me-003',
    title: "Israel's Drip Irrigation Technology Feeds Millions Across Arid Africa",
    summary: "The drip irrigation technology pioneered in Israel's Negev desert has been adapted by smallholder farmers across sub-Saharan Africa, dramatically improving crop yields with a fraction of the water.",
    content: "Drip irrigation — the technology that transformed Israel's desert into a global agricultural powerhouse — is now being deployed at scale by smallholder farmers across sub-Saharan Africa and South Asia. A simplified, affordable version delivers water directly to plant roots through perforated tubes, reducing water use by up to 70% while doubling or tripling yields.",
    sourceUrl: 'https://www.haaretz.com/israel-news/2023-05-22/ty-article/israeli-drip-irrigation-africa',
    sourceName: 'Haaretz',
    region: 'Middle East',
    country: 'Israel',
    category: 'Science & Tech',
    tags: ['drip irrigation', 'Israel', 'agriculture', 'Africa', 'innovation'],
    publishedAt: '2023-05-22T10:00:00Z',
    imageUrl: 'https://picsum.photos/seed/me003/800/450',
    positivityScore: 89,
    trending: false,
    featured: false,
    readTime: 4,
  },
  {
    id: 'me-004',
    title: "Qatar's Education City Graduates First Generation of Home-Grown Scientists",
    summary: "Qatar's Education City — home to campuses of eight world-leading universities — has graduated its first generation of home-grown scientists, engineers, and doctors, transforming the country's human capital.",
    content: "Qatar's Education City, a 2,500-acre campus that hosts branch universities of Carnegie Mellon, Georgetown, Northwestern, and five other world-leading institutions, has now produced its first large cohort of graduates in medicine, science, engineering, law, and the arts. A large majority of graduates are women — a striking shift in one of the Gulf's most traditional societies.",
    sourceUrl: 'https://www.aljazeera.com/news/2023/5/20/qatar-education-city',
    sourceName: 'Al Jazeera',
    region: 'Middle East',
    country: 'Qatar',
    category: 'Education',
    tags: ['education', 'Qatar', 'university', 'women', 'Gulf'],
    publishedAt: '2023-05-20T10:00:00Z',
    imageUrl: 'https://picsum.photos/seed/me004/800/450',
    positivityScore: 88,
    trending: false,
    featured: false,
    readTime: 3,
  },
  {
    id: 'me-005',
    title: "Oman's Sea Turtle Nesting Beaches Set Record After Two Decades of Protection",
    summary: "Oman's Ras Al Jinz turtle sanctuary recorded the highest number of green sea turtle nestings in its history, after 20 years of community-led conservation that turned former hunters into wildlife guardians.",
    content: "Oman's Ras Al Jinz Turtle Reserve on the Arabian Sea coast recorded its highest ever number of green turtle nests — over 30,000 in a single season — following two decades of government protection and community conservation programs. The local community transformed from one that historically hunted turtles into a centre of eco-tourism and conservation expertise.",
    sourceUrl: 'https://www.independent.co.uk/travel/middle-east/oman-turtle-conservation/',
    sourceName: 'The Independent',
    region: 'Middle East',
    country: 'Oman',
    category: 'Environment',
    tags: ['sea turtles', 'Oman', 'conservation', 'eco-tourism'],
    publishedAt: '2024-01-25T09:00:00Z',
    imageUrl: 'https://picsum.photos/seed/me005/800/450',
    positivityScore: 94,
    trending: false,
    featured: false,
    readTime: 3,
  },
  {
    id: 'me-006',
    title: "Lebanon's Seed Bank Safeguards 2,000 Ancient Crop Varieties from Extinction",
    summary: "A Lebanese research centre has preserved over 2,000 varieties of wheat, lentils, and ancient grains from the Fertile Crescent, protecting the genetic diversity future farmers may need to survive climate change.",
    content: "The International Center for Agricultural Research in the Dry Areas maintains a living collection of over 2,000 crop varieties that originated in the Fertile Crescent — the cradle of agriculture. The seed bank preserves ancient varieties of wheat, barley, chickpea, and lentil that are drought-resistant, disease-resistant, or suited to specific soils in ways that modern commercial crops are not.",
    sourceUrl: 'https://www.icarda.org/media/news',
    sourceName: 'ICARDA',
    region: 'Middle East',
    country: 'Lebanon',
    category: 'Science & Tech',
    tags: ['seed bank', 'Lebanon', 'food security', 'crop diversity', 'climate'],
    publishedAt: '2024-02-14T10:00:00Z',
    imageUrl: 'https://picsum.photos/seed/me006/800/450',
    positivityScore: 89,
    trending: false,
    featured: false,
    readTime: 4,
  },

  // ── Oceania ───────────────────────────────────────────────────────────────
  {
    id: 'oc-001',
    title: 'Great Barrier Reef Records Highest Coral Cover in 36 Years of Surveys',
    summary: "Australia's Great Barrier Reef showed its highest coral coverage since surveys began 36 years ago in parts of the northern reef, giving conservation scientists cautious hope for the ocean's most biodiverse ecosystem.",
    content: "Australia's Institute of Marine Science reported that parts of the Great Barrier Reef recorded the highest coral coverage in 36 years of systematic monitoring. The northern and central sections showed significant recovery, with some areas reaching 33% hard coral cover. Scientists credit reduced crown-of-thorns starfish numbers and natural coral resilience.",
    sourceUrl: 'https://www.bbc.com/news/world-australia-62027636',
    sourceName: 'BBC News',
    region: 'Oceania',
    country: 'Australia',
    category: 'Environment',
    tags: ['Great Barrier Reef', 'coral', 'Australia', 'conservation'],
    publishedAt: '2023-08-04T09:00:00Z',
    imageUrl: 'https://picsum.photos/seed/oc001/800/450',
    positivityScore: 90,
    trending: true,
    featured: true,
    readTime: 4,
  },
  {
    id: 'oc-002',
    title: "New Zealand's Māori Language Reaches One Million Speakers Milestone",
    summary: 'The Māori language (Te Reo Māori), once feared extinct, has reached one million speakers following generations of revival work through immersion schools, broadcasting, and official language status.',
    content: "Te Reo Māori has reached the milestone of one million speakers following an extraordinary multi-generational revival effort. Once actively suppressed in schools, the language is now co-official with English, taught in dedicated immersion schools, broadcast on a dedicated Māori television channel, and celebrated in national cultural events.",
    sourceUrl: 'https://www.theguardian.com/world/2023/oct/09/maori-language-speakers-one-million-new-zealand',
    sourceName: 'The Guardian',
    region: 'Oceania',
    country: 'New Zealand',
    category: 'Arts & Culture',
    tags: ['Māori', 'language revival', 'New Zealand', 'indigenous culture'],
    publishedAt: '2023-10-09T09:00:00Z',
    imageUrl: 'https://picsum.photos/seed/oc002/800/450',
    positivityScore: 95,
    trending: false,
    featured: true,
    readTime: 4,
  },
  {
    id: 'oc-003',
    title: 'Australia Returns Vast Sacred Land to Aboriginal Custodians in Historic Deal',
    summary: "Australia's federal government returned over 2 million hectares of the Northern Territory to Aboriginal traditional owners in one of the largest land rights handbacks in the nation's history.",
    content: "The Australian government completed the transfer of 2 million hectares of land in the Northern Territory to its Aboriginal traditional owners, recognising the continuous custodial relationship between indigenous peoples and country their ancestors have managed for tens of thousands of years. Under the terms, traditional owners will work with the government as co-managers of national parks within the boundary.",
    sourceUrl: 'https://www.abc.net.au/news/2023-10-26/aboriginal-land-handback-northern-territory/102987460',
    sourceName: 'ABC News Australia',
    region: 'Oceania',
    country: 'Australia',
    category: 'Community',
    tags: ['land rights', 'Aboriginal', 'Australia', 'indigenous', 'reconciliation'],
    publishedAt: '2023-10-26T11:00:00Z',
    imageUrl: 'https://picsum.photos/seed/oc003/800/450',
    positivityScore: 91,
    trending: false,
    featured: false,
    readTime: 4,
  },
  {
    id: 'oc-004',
    title: "Fiji's Community-Led Coral Reef Restoration Becomes Global Model",
    summary: 'Fijian villagers have restored over 100 hectares of bleached coral reef using locally designed coral nurseries and seasonal fishing bans, reversing damage that scientists had thought permanent.',
    content: "Communities in Fiji have successfully restored over 100 hectares of coral reef that had been bleached and damaged by warming seas and storm damage. Working with marine biologists, villagers grow coral fragments in underwater nurseries, then transplant them to degraded sections of reef. Seasonal fishing bans — enforced by the communities themselves — allow fish populations to recover, which in turn helps the coral grow.",
    sourceUrl: 'https://www.positive.news/environment/coral-reef-restoration/',
    sourceName: 'Positive News',
    region: 'Oceania',
    country: 'Fiji',
    category: 'Environment',
    tags: ['coral reef', 'Fiji', 'restoration', 'marine conservation'],
    publishedAt: '2024-01-18T10:00:00Z',
    imageUrl: 'https://picsum.photos/seed/oc004/800/450',
    positivityScore: 94,
    trending: false,
    featured: false,
    readTime: 3,
  },
  {
    id: 'oc-005',
    title: 'New Zealand Bans Offshore Oil and Gas Exploration to Protect Coastlines',
    summary: "New Zealand became one of the first countries to ban all new offshore oil and gas exploration, safeguarding its pristine coastlines and signalling a definitive pivot toward a renewable-powered future.",
    content: "New Zealand enacted legislation permanently banning all new offshore oil and gas exploration, protecting the country's extensive Exclusive Economic Zone from drilling activity that poses unacceptable risks to marine ecosystems, including breeding grounds for southern right whales and Māui dolphins. The government simultaneously announced accelerated investment in wind and geothermal energy.",
    sourceUrl: 'https://www.theguardian.com/world/2018/apr/12/new-zealand-bans-new-offshore-oil-and-gas-exploration',
    sourceName: 'The Guardian',
    region: 'Oceania',
    country: 'New Zealand',
    category: 'Environment',
    tags: ['fossil fuels', 'New Zealand', 'offshore drilling', 'marine protection'],
    publishedAt: '2023-06-01T09:00:00Z',
    imageUrl: 'https://picsum.photos/seed/oc005/800/450',
    positivityScore: 90,
    trending: false,
    featured: false,
    readTime: 3,
  },
  {
    id: 'oc-006',
    title: 'Papua New Guinea Protects 5 Million Hectares of Ancient Rainforest',
    summary: "Papua New Guinea granted protected status to 5 million hectares of its ancient rainforest — the world's third largest — with indigenous communities taking the lead in managing and monitoring the land.",
    content: "Papua New Guinea announced the formal protection of 5 million hectares of its ancient tropical rainforest, putting it under a community-led conservation agreement that pays indigenous landowners to act as forest guardians. PNG's rainforests harbour extraordinary biodiversity including species found nowhere else — tree kangaroos, birds of paradise, and giant orchids.",
    sourceUrl: 'https://www.wwf.org.au/news/news/2023/png-forest-protection',
    sourceName: 'WWF Australia',
    region: 'Oceania',
    country: 'Papua New Guinea',
    category: 'Environment',
    tags: ['rainforest', 'Papua New Guinea', 'indigenous conservation', 'biodiversity'],
    publishedAt: '2024-03-12T10:00:00Z',
    imageUrl: 'https://picsum.photos/seed/oc006/800/450',
    positivityScore: 93,
    trending: false,
    featured: false,
    readTime: 4,
  },
]

let fetchedArticles: Article[] = []

// Load articles from the API JSON file
async function loadFetchedArticles() {
  try {
    const response = await fetch('/articles.json')
    if (response.ok) {
      const data = await response.json()
      if (data.results && Array.isArray(data.results)) {
        // Transform API articles to match Article type
        fetchedArticles = data.results.slice(0, 50).map((apiArticle: any, index: number) => ({
          id: `live-${apiArticle.article_id || index}`,
          title: apiArticle.title,
          summary: apiArticle.description || '',
          content: apiArticle.content || 'Full article available at source',
          sourceUrl: apiArticle.link,
          sourceName: apiArticle.source_name || 'News',
          region: apiArticle.country?.[0] === 'united states of america' ? 'North America' : 'Global',
          country: apiArticle.country?.[0] || 'Global',
          category: apiArticle.category?.[0] || 'News',
          tags: apiArticle.keywords || [],
          publishedAt: apiArticle.pubDate || new Date().toISOString(),
          imageUrl: apiArticle.image_url || `https://picsum.photos/seed/${apiArticle.article_id}/800/450`,
          positivityScore: 75,
          trending: false,
          featured: false,
          readTime: 3,
        }))
      }
    }
  } catch (error) {
    console.error('Failed to load fetched articles:', error)
  }
}

// Call this on module load
loadFetchedArticles()

export const articles: Article[] = []

// Combined getter that includes both types
export function getAllArticles(): Article[] {
  return [...fetchedArticles, ...defaultArticles]
}

export function getFeaturedArticles(): Article[] {
  return getAllArticles().filter(a => a.featured).slice(0, 4)
}

export function getTrendingArticles(): Article[] {
  return getAllArticles().filter(a => a.trending).slice(0, 20)
}

export function getArticleById(id: string): Article | undefined {
  return getAllArticles().find(a => a.id === id)
}

export function getArticlesByRegion(region: string): Article[] {
  if (region === 'All') return getAllArticles()
  return getAllArticles().filter(a => a.region === region)
}

export function getArticlesByCategory(category: string): Article[] {
  if (category === 'All') return getAllArticles()
  return getAllArticles().filter(a => a.category === category)
}

export function searchArticles(query: string, region?: string, category?: string): Article[] {
  let results = getAllArticles()

  if (region && region !== 'All') {
    results = results.filter(a => a.region === region)
  }

  if (category && category !== 'All') {
    results = results.filter(a => a.category === category)
  }

  if (query) {
    const q = query.toLowerCase()
    results = results.filter(a =>
      a.title.toLowerCase().includes(q) ||
      a.summary.toLowerCase().includes(q) ||
      a.tags.some(t => t.toLowerCase().includes(q)) ||
      a.country.toLowerCase().includes(q) ||
      a.sourceName.toLowerCase().includes(q)
    )
  }

  return results
}

export function getRelatedArticles(article: Article, limit = 3): Article[] {
  return getAllArticles()
    .filter(a => a.id !== article.id && (a.category === article.category || a.region === article.region))
    .slice(0, limit)
}

export function getArticlesByIds(ids: string[]): Article[] {
  return getAllArticles().filter(a => ids.includes(a.id))
}
